Repository rust-lang/libc, pull requests merged in 2020-10, with the labels that each got.

#1924 Upload documentation to gh-pages from GHA
  .github/workflows/docs.yml
  ci/azure-master.yml
Labels: S-waiting-on-review

#1922 Add clock_nanosleep to freebsd and netbsd
  src/unix/bsd/freebsdlike/freebsd/freebsd12/mod.rs
  src/unix/bsd/netbsdlike/netbsd/mod.rs
Labels: S-waiting-on-review

#1926 Allow contributors to label issues via rustbot
  triagebot.toml
Labels: S-waiting-on-bors

#1878 process_vm_readv, process_vm_writev should be available on android
  libc-test/build.rs
  src/unix/linux_like/android/mod.rs
Labels: S-waiting-on-author

#1703 Add deprecation notice to `af_alg_iv::as_slice` and trait implementations that depend on it
  src/macros.rs
  src/unix/linux_like/android/mod.rs
  src/unix/linux_like/linux/mod.rs
Labels: S-waiting-on-author

#1930 Revive `i686-linux-android` CI
  .github/workflows/bors.yml
  ci/docker/aarch64-linux-android/Dockerfile
  ci/docker/arm-linux-androideabi/Dockerfile
  ci/docker/i686-linux-android/Dockerfile
Labels: S-waiting-on-review

#1931 Revive `powerpc-unknown-linux-gnu` CI
  .github/workflows/bors.yml
Labels: S-waiting-on-review

#1936 Drop FreeBSD 10 and add FreeBSD 13 image on Cirrus CI
  .cirrus.yml
  ci/run.sh
  libc-test/build.rs
Labels: S-waiting-on-bors

#1939 Add freebsd nmount
  src/unix/bsd/freebsdlike/freebsd/freebsd11/mod.rs
  src/unix/bsd/freebsdlike/freebsd/freebsd12/mod.rs
  src/unix/bsd/freebsdlike/freebsd/mod.rs
Labels: S-waiting-on-bors

#1832 Android: Add preadv and pwritev.
  src/unix/linux_like/android/mod.rs
Labels: S-waiting-on-bors

#1934 Run build test for `x86_64-unknown-redox`
  .github/workflows/bors.yml
  ci/build.sh
  ci/docker/x86_64-unknown-redox/Dockerfile
  libc-test/build.rs
Labels: S-waiting-on-bors

#1932 Add some more targets for build testing
  ci/build.sh
Labels: S-waiting-on-bors

#1935 Revive `sparc-unknown-linux-gnu` CI
  ci/build.sh
  src/unix/linux_like/linux/gnu/b32/mod.rs
  src/unix/linux_like/linux/gnu/b32/sparc/mod.rs
Labels: S-waiting-on-bors

#1946 Rollup of 3 pull requests
  .github/workflows/bors.yml
  src/unix/linux_like/linux/gnu/mod.rs
  src/unix/linux_like/linux/mod.rs
Labels: S-waiting-on-bors

#1945 Disable libc-test for MIPS64 for now
  .github/workflows/bors.yml
Labels: S-waiting-on-bors

#1944 Include sendfile64() for Linux
  src/unix/linux_like/linux/mod.rs
Labels: S-waiting-on-bors

#1943 Add definitions for Linux debug related MAGIC
  src/unix/linux_like/linux/gnu/mod.rs
Labels: S-waiting-on-bors

#1947 Add lockf() operations to Android
  src/unix/linux_like/android/mod.rs
Labels: S-waiting-on-bors

#1949 Add issue templates with new style
  .github/ISSUE_TEMPLATE/api_request.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: S-waiting-on-bors

#1951 Add constants of socket options
  src/unix/linux_like/linux/gnu/b64/x86_64/mod.rs
Labels: S-waiting-on-bors

#1954 Unpin the `cc` crate version
  ci/docker/aarch64-linux-android/Dockerfile
  ci/docker/arm-linux-androideabi/Dockerfile
  ci/docker/i686-linux-android/Dockerfile
  libc-test/Cargo.toml
Labels: S-waiting-on-bors

#1955 Bring the MUSL version of siginfo_t up-to-date.
  src/unix/linux_like/linux/musl/mod.rs
Labels: S-waiting-on-bors

#1902 linux: Add definitions for Multipath TCP
  libc-test/build.rs
  src/unix/linux_like/android/mod.rs
  src/unix/linux_like/emscripten/mod.rs
  src/unix/linux_like/linux/mod.rs
  src/unix/linux_like/mod.rs
Labels: S-waiting-on-bors

#1941 Revive tests for MIPS64
  .github/workflows/bors.yml
  ci/run.sh
Labels: S-waiting-on-bors

#1956 Add a deprecation note to `time_t` on musl
  src/unix/linux_like/linux/musl/mod.rs
  src/unix/mod.rs
Labels: S-waiting-on-bors

#1958 Allow `deprecated` attribute on `f!` macros to fix dragonfly build
  src/macros.rs
  src/unix/bsd/freebsdlike/dragonfly/errno.rs
Labels: S-waiting-on-bors

#1959 Release 0.2.80
  Cargo.toml
Labels: S-waiting-on-bors

#1961 Rollup of 2 pull requests
  ci/build.sh
  libc-test/build.rs
  src/unix/bsd/freebsdlike/freebsd/mod.rs
  src/unix/bsd/freebsdlike/mod.rs
  src/unix/bsd/netbsdlike/netbsd/mod.rs
  src/unix/bsd/netbsdlike/openbsd/mod.rs
Labels: S-waiting-on-bors

#1953 Add dl_iterate_phdr to some BSD OSs
  libc-test/build.rs
  src/unix/bsd/freebsdlike/freebsd/mod.rs
  src/unix/bsd/freebsdlike/mod.rs
  src/unix/bsd/netbsdlike/netbsd/mod.rs
  src/unix/bsd/netbsdlike/openbsd/mod.rs
Labels: S-waiting-on-bors

#1960 Disable `sparc-unknown-linux-gnu` for now
  ci/build.sh
Labels: S-waiting-on-bors

#1963 Add endservent, getservbyport, getservent, setservent
  src/unix/mod.rs
Labels: S-waiting-on-bors

#1962 Update redox socket constants
  src/unix/redox/mod.rs
Labels: S-waiting-on-bors

#1964 Add more TCP options for solaris systems.
  src/unix/solarish/illumos.rs
  src/unix/solarish/mod.rs
  src/unix/solarish/solaris.rs
Labels: S-waiting-on-bors

#1965 Update GHA Ubuntu version to 20.04
  .github/workflows/bors.yml
  .github/workflows/docs.yml
  .github/workflows/main.yml
  ci/install-rust.sh
  ci/run-docker.sh
  ci/style.sh
Labels: S-waiting-on-bors

#1966 Update to FreeBSD 12.2
  .cirrus.yml
  libc-test/build.rs
Labels: S-waiting-on-bors
