Repository rust-lang/libc, pull requests merged in 2023-09, with the labels that each got.

#3351 libc 0.2.148
  Cargo.toml
Labels: S-waiting-on-review

#3314 update libc-test and its libc dependency to 0.2.148
  libc-test/Cargo.toml
Labels: S-waiting-on-review

#3358 Disable 1.13 CI
  .github/workflows/bors.yml
Labels: S-waiting-on-bors

#3333 Add teeos libc
  src/lib.rs
  src/teeos/mod.rs
Labels: S-waiting-on-bors

#3354 Added SIOCSIFNAME
  src/unix/linux_like/linux/mod.rs
Labels: S-waiting-on-bors

#3346 copyfile apple api update
  libc-test/semver/apple.txt
  src/unix/bsd/apple/mod.rs
Labels: S-waiting-on-bors

#3348 Hermit updates
  Cargo.toml
  ci/build.sh
  src/hermit/mod.rs
  src/unix/hermit/aarch64.rs
  src/unix/hermit/mod.rs
  src/unix/hermit/x86_64.rs
  src/unix/mod.rs
Labels: S-waiting-on-bors

#3337 Add F_PUNCHHOLE and fpunchhole_t
  libc-test/semver/apple.txt
  src/unix/bsd/apple/mod.rs
Labels: S-waiting-on-bors

#3308 Fix compatibility with Emscripten >= 3.1.44
  libc-test/build.rs
  libc-test/semver/emscripten.txt
  src/unix/linux_like/emscripten/lfs64.rs
  src/unix/linux_like/emscripten/mod.rs
  src/unix/linux_like/mod.rs
Labels: S-waiting-on-bors

#3326 freebsd adding few mmap constants related to page alignment
  libc-test/semver/freebsd.txt
  src/unix/bsd/freebsdlike/freebsd/mod.rs
Labels: S-waiting-on-bors

#3347 Redox pthreads
  src/unix/redox/mod.rs
Labels: breakage-candidate, S-waiting-on-bors

#3340 linux MADV_COLLAPSE addition
  libc-test/build.rs
  libc-test/semver/linux-gnu.txt
  src/unix/linux_like/linux/gnu/mod.rs
Labels: S-waiting-on-bors

#3288 android adding few more pthread api calls.
  libc-test/build.rs
  libc-test/semver/android.txt
  src/unix/linux_like/android/mod.rs
Labels: S-waiting-on-bors

#3330 Declare `pthread_attr_setguardsize` and `pthread_attr_getstacksize`.
  libc-test/semver/dragonfly.txt
  libc-test/semver/freebsd.txt
  libc-test/semver/fuchsia.txt
  libc-test/semver/linux.txt
  libc-test/semver/netbsd.txt
  libc-test/semver/openbsd.txt
  libc-test/semver/unix.txt
  src/fuchsia/mod.rs
  src/unix/aix/mod.rs
  src/unix/bsd/freebsdlike/mod.rs
  src/unix/bsd/netbsdlike/netbsd/mod.rs
  src/unix/bsd/netbsdlike/openbsd/mod.rs
  src/unix/haiku/mod.rs
  src/unix/linux_like/android/mod.rs
  src/unix/linux_like/linux/mod.rs
  src/unix/mod.rs
  src/unix/nto/mod.rs
Labels: S-waiting-on-bors

#3284 Add missing PS Vita definitions, fix some unused ones
  src/unix/mod.rs
  src/unix/newlib/aarch64/mod.rs
  src/unix/newlib/arm/mod.rs
  src/unix/newlib/espidf/mod.rs
  src/unix/newlib/generic.rs
  src/unix/newlib/horizon/mod.rs
  src/unix/newlib/mod.rs
  src/unix/newlib/powerpc/mod.rs
  src/unix/newlib/vita/mod.rs
Labels: S-waiting-on-bors

#3362 Drop `armv7-apple-ios` target support
  ci/build.sh
Labels: S-waiting-on-bors

#3368 backtrace definitions and support for getmntinfo and getvfsstat
  libc-test/semver/netbsd.txt
  src/unix/bsd/netbsdlike/netbsd/mod.rs
Labels: S-waiting-on-bors

#3365 apple fcntl update.
  libc-test/semver/apple.txt
  src/unix/bsd/apple/mod.rs
Labels: S-waiting-on-bors

#3366 Added socketpair and pipe2 for Vita target
  src/unix/mod.rs
  src/unix/newlib/vita/mod.rs
Labels: S-waiting-on-bors

#3332 Added additional Ethernet Protocol Ids for fuchsia
  libc-test/semver/fuchsia.txt
  src/fuchsia/mod.rs
Labels: S-waiting-on-bors

#3341 timerfd api for freebsd 14.
  libc-test/build.rs
  src/unix/bsd/freebsdlike/freebsd/mod.rs
Labels: S-waiting-on-bors

#3364 haiku adding pthread GNU part
  src/unix/haiku/mod.rs
Labels: S-waiting-on-bors
