Repository rust-lang/libc, pull requests merged in 2023-05, with the labels that each got.

#3230 Added getentropy to vita target
  src/unix/newlib/vita/mod.rs
Labels: S-waiting-on-bors

#3228 redox: add grp.h and pwd.h functions for the users crate
  libc-test/semver/redox.txt
  src/unix/redox/mod.rs
Labels: S-waiting-on-bors

#3232 redox add few more poll constants
  src/unix/redox/mod.rs
Labels: S-waiting-on-bors

#3231 freebsd add few more procctl x86_64 constants.
  src/unix/bsd/freebsdlike/freebsd/freebsd14/x86_64.rs
Labels: S-waiting-on-bors

#3224 Add `MSG_WAITFORONE` to freebsd and openbsd
  libc-test/semver/freebsd.txt
  libc-test/semver/openbsd.txt
  src/unix/bsd/freebsdlike/freebsd/mod.rs
  src/unix/bsd/netbsdlike/openbsd/mod.rs
Labels: S-waiting-on-bors

#3206 Add PF_ROUTE-related structures on Apple systems
  src/unix/bsd/apple/mod.rs
Labels: S-waiting-on-bors

#3237 linux_like: Add missing constants for loongarch64
  src/unix/linux_like/linux/arch/generic/mod.rs
Labels: S-waiting-on-bors

#3051 linux: add rtnetlink ifinfomsg attribute enumerals
  libc-test/build.rs
  libc-test/semver/linux.txt
  src/unix/linux_like/linux/mod.rs
Labels: S-waiting-on-bors

#2999 add major/minor on BSDs/illumos
  libc-test/build.rs
  src/unix/bsd/freebsdlike/dragonfly/mod.rs
  src/unix/bsd/freebsdlike/freebsd/freebsd11/mod.rs
  src/unix/bsd/freebsdlike/freebsd/freebsd12/mod.rs
  src/unix/bsd/freebsdlike/freebsd/freebsd13/mod.rs
  src/unix/bsd/freebsdlike/freebsd/freebsd14/mod.rs
  src/unix/bsd/netbsdlike/netbsd/mod.rs
  src/unix/bsd/netbsdlike/openbsd/mod.rs
  src/unix/solarish/mod.rs
Labels: S-waiting-on-bors

#3236 Release 0.2.143
  Cargo.toml
  libc-test/Cargo.toml
Labels: S-waiting-on-bors

#3233 Add missing <proc.h> constants for darwin
  src/unix/bsd/apple/mod.rs
Labels: S-waiting-on-bors

#3238 more bsd things: kenv, setlogin, reboot, SCM_ constants
  libc-test/build.rs
  libc-test/semver/dragonfly.txt
  libc-test/semver/freebsd.txt
  libc-test/semver/netbsd.txt
  libc-test/semver/openbsd.txt
  src/unix/bsd/freebsdlike/dragonfly/mod.rs
  src/unix/bsd/freebsdlike/freebsd/mod.rs
  src/unix/bsd/freebsdlike/mod.rs
  src/unix/bsd/mod.rs
Labels: S-waiting-on-bors

#3241 Constify `CMSG_LEN` for all targets.
  src/fuchsia/mod.rs
  src/unix/aix/mod.rs
  src/unix/bsd/apple/mod.rs
  src/unix/bsd/freebsdlike/dragonfly/mod.rs
  src/unix/bsd/freebsdlike/freebsd/mod.rs
  src/unix/bsd/netbsdlike/netbsd/mod.rs
  src/unix/bsd/netbsdlike/openbsd/mod.rs
  src/unix/haiku/mod.rs
  src/unix/linux_like/mod.rs
  src/unix/nto/mod.rs
  src/unix/solarish/mod.rs
  src/vxworks/mod.rs
Labels: S-waiting-on-bors

#3239 Update crate version to 0.2.144
  Cargo.toml
  libc-test/Cargo.toml
Labels: S-waiting-on-bors

#3244 redox add sig(timed)wait calls
  libc-test/semver/redox.txt
  src/unix/redox/mod.rs
Labels: S-waiting-on-bors

#3246 Fix loongarch64 bindings
  libc-test/semver/linux-gnu-loongarch64.txt
  libc-test/semver/linux-loongarch64.txt
  src/unix/linux_like/linux/gnu/b64/loongarch64/align.rs
  src/unix/linux_like/linux/gnu/b64/loongarch64/mod.rs
Labels: S-waiting-on-bors

#3247 Add linux canxl constants and canxl frame struct
  libc-test/build.rs
  libc-test/semver/linux.txt
  src/unix/linux_like/linux/align.rs
  src/unix/linux_like/linux/mod.rs
Labels: S-waiting-on-review

#3249 Change branch references to HEAD where possible or main otherwise
  .github/workflows/bors.yml
  .github/workflows/docs.yml
  .github/workflows/main.yml
  README.md
  ci/README.md
  ci/linux-s390x.sh
  ci/rust.css
  src/unix/bsd/apple/mod.rs
  src/unix/bsd/freebsdlike/dragonfly/mod.rs
  src/unix/bsd/freebsdlike/mod.rs
  src/unix/bsd/netbsdlike/netbsd/mod.rs
  src/unix/bsd/netbsdlike/openbsd/mod.rs
  src/unix/haiku/mod.rs
  src/unix/linux_like/android/mod.rs
  src/unix/newlib/mod.rs
  triagebot.toml
Labels: S-waiting-on-bors

#3137 linux/musl/s390x: change f_* constants to uint from ulong
  src/unix/linux_like/linux/musl/b64/s390x.rs
Labels: breakage-candidate, S-waiting-on-bors

#3252 android: add memmem
  libc-test/semver/android.txt
  src/unix/linux_like/android/mod.rs
Labels: S-waiting-on-bors

#3251 redox adding lockf flags
  src/unix/redox/mod.rs
Labels: S-waiting-on-bors

#3250 Add ucred struct and field type aliases for redox
  src/unix/redox/mod.rs
Labels: S-waiting-on-bors

#3254 Skip round-trip tests for structs with FAMs
  libc-test/build.rs
Labels: S-waiting-on-bors

#3256 Fixed pthread_attr_t and pthread_rwlockattr_t for newlib
  src/unix/newlib/mod.rs
Labels: S-waiting-on-bors

#2935 Alias all LFS64 symbols to their non-LFS64 counterparts on musl
  libc-test/build.rs
  src/unix/linux_like/linux/mod.rs
  src/unix/linux_like/linux/musl/b32/riscv32/mod.rs
  src/unix/linux_like/linux/musl/b64/riscv64/mod.rs
  src/unix/linux_like/linux/musl/lfs64.rs
  src/unix/linux_like/linux/musl/mod.rs
  src/unix/linux_like/mod.rs
Labels: S-waiting-on-bors
