Repository rust-lang/libc, pull requests merged in 2024-11, with the labels that each got.

#4002 Don't pass -lc to Emscripten, it breaks
  src/unix/mod.rs
Labels: S-waiting-on-review, stable-nominated

#4000 ci: add support for loongarch64-unknown-linux-gnu
  .github/workflows/full_ci.yml
  ci/docker/loongarch64-unknown-linux-gnu/Dockerfile
Labels: S-waiting-on-review, stable-nominated

#3864 Fix tests on Solaris
  libc-test/build.rs
  libc-test/semver/TODO-unix.txt
  libc-test/semver/unix.txt
  src/unix/mod.rs
  src/unix/solarish/illumos.rs
  src/unix/solarish/mod.rs
  src/unix/solarish/solaris.rs
  src/unix/solarish/x86_64.rs
  src/unix/solarish/x86_common.rs
Labels: S-waiting-on-review

#4003 NuttX: add pthread_[get/set]name_np functions
  src/unix/nuttx/mod.rs
Labels: S-waiting-on-review

#3991 haiku: add getentropy
  src/unix/haiku/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3942 Add Trusty OS support
  libc-test/semver/trusty.txt
  src/lib.rs
  src/trusty.rs
Labels: S-waiting-on-review, stable-nominated

#3922 Linux: epoll: add busy polling parameters
  libc-test/build.rs
  libc-test/semver/linux.txt
  src/unix/linux_like/linux/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3916 Apple: add `host_cpu_load_info`
  libc-test/semver/apple.txt
  src/unix/bsd/apple/mod.rs
Labels: S-waiting-on-review, stable-nominated

#4005 [0.2] Backports
  libc-test/semver/illumos.txt
  libc-test/semver/wasi-p2.txt
  src/unix/hurd/mod.rs
  src/unix/newlib/rtems/mod.rs
  src/unix/solarish/illumos.rs
  src/wasi/p2.rs
Labels: S-waiting-on-review

#4007 [0.2] Backports
  libc-test/build.rs
  libc-test/test/cmsg.rs
  libc-test/test/errqueue.rs
  libc-test/test/linux_elf.rs
  libc-test/test/linux_fcntl.rs
  libc-test/test/linux_if_arp.rs
  libc-test/test/linux_ipv6.rs
  libc-test/test/linux_kernel_version.rs
  libc-test/test/linux_strerror_r.rs
  libc-test/test/linux_termios.rs
  libc-test/test/main.rs
  libc-test/test/makedev.rs
  libc-test/test/semver.rs
  libc-test/test/sigrt.rs
Labels: S-waiting-on-review

#4008 [0.2] Backports
  .cirrus.yml
Labels: S-waiting-on-review

#3996 freebsd: add CLOSE_RANGE_CLOEXEC flag
  libc-test/semver/freebsd.txt
  src/unix/bsd/freebsdlike/freebsd/mod.rs
Labels: S-waiting-on-review, stable-nominated

#4004 Fix definition of FNM_CASEFOLD for Illumos/Solaris
  src/unix/mod.rs
Labels: S-waiting-on-review, stable-nominated

#4011 [0.2] Backports
  build.rs
  libc-test/semver/trusty.txt
  src/lib.rs
  src/trusty.rs
  src/unix/haiku/mod.rs
  src/unix/mod.rs
  src/unix/newlib/mod.rs
  src/unix/nuttx/mod.rs
Labels: S-waiting-on-review

#4014 [0.2] Backports
  Cargo.toml
  ci/build.sh
  libc-test/build.rs
  libc-test/semver/apple.txt
  libc-test/semver/linux.txt
  src/unix/bsd/apple/mod.rs
  src/unix/linux_like/linux/mod.rs
Labels: S-waiting-on-review

#4013 Remove the `wasm32-wasi` target
  Cargo.toml
  ci/build.sh
Labels: S-waiting-on-review

#4015 [0.2] Format all markdown files to rewrap text
  CONTRIBUTING.md
  README.md
  ci/README.md
  libc-test/semver/README.md
Labels: S-waiting-on-review

#3960 feat: add `ioctl` flags in `linux/if_tun.h`
  libc-test/semver/linux-gnu.txt
  libc-test/semver/linux.txt
  src/unix/linux_like/linux/arch/generic/mod.rs
  src/unix/linux_like/linux/arch/mips/mod.rs
  src/unix/linux_like/linux/arch/powerpc/mod.rs
  src/unix/linux_like/linux/arch/sparc/mod.rs
  src/unix/linux_like/linux/gnu/mod.rs
  src/unix/linux_like/linux/mod.rs
Labels: S-waiting-on-review, stable-nominated

#4016 [0.2] Convert mode_t constants to octal
  src/fuchsia/mod.rs
  src/solid/mod.rs
  src/unix/aix/mod.rs
  src/unix/bsd/apple/mod.rs
  src/unix/bsd/freebsdlike/mod.rs
  src/unix/bsd/netbsdlike/mod.rs
  src/unix/haiku/mod.rs
  src/unix/hurd/mod.rs
  src/unix/linux_like/emscripten/mod.rs
  src/unix/linux_like/linux/mod.rs
  src/unix/linux_like/mod.rs
  src/unix/mod.rs
  src/unix/newlib/mod.rs
  src/unix/nto/mod.rs
  src/unix/redox/mod.rs
  src/unix/solarish/mod.rs
  src/vxworks/mod.rs
  src/wasi/mod.rs
  src/windows/mod.rs
Labels: S-waiting-on-review

#4018 Ensure that semver files are always sorted in CI
  ci/style.sh
  libc-test/semver/android-aarch64.txt
  libc-test/semver/android.txt
  libc-test/semver/apple.txt
  libc-test/semver/dragonfly.txt
  libc-test/semver/emscripten.txt
  libc-test/semver/freebsd.txt
  libc-test/semver/fuchsia.txt
  libc-test/semver/hermit.txt
  libc-test/semver/illumos.txt
  libc-test/semver/linux-aarch64.txt
  libc-test/semver/linux-gnu-loongarch64.txt
  libc-test/semver/linux-gnu-riscv64gc.txt
  libc-test/semver/linux-gnu.txt
  libc-test/semver/linux-i686.txt
  libc-test/semver/linux-loongarch64.txt
  libc-test/semver/linux-musl.txt
  libc-test/semver/linux-riscv64gc.txt
  libc-test/semver/linux-x86_64.txt
  libc-test/semver/linux.txt
  libc-test/semver/macos-aarch64.txt
  libc-test/semver/netbsd-aarch64.txt
  libc-test/semver/netbsd-mips.txt
  libc-test/semver/netbsd-x86_64.txt
  libc-test/semver/netbsd.txt
  libc-test/semver/openbsd.txt
  libc-test/semver/redox.txt
  libc-test/semver/trusty.txt
  libc-test/semver/unix.txt
  libc-test/semver/wasi-p2.txt
  libc-test/semver/wasi.txt
  libc-test/semver/windows.txt
Labels: S-waiting-on-review, stable-nominated

#4019 [0.2] Ensure that semver files are always sorted in CI
  ci/style.sh
  libc-test/semver/android-aarch64.txt
  libc-test/semver/android.txt
  libc-test/semver/apple.txt
  libc-test/semver/dragonfly.txt
  libc-test/semver/emscripten.txt
  libc-test/semver/freebsd.txt
  libc-test/semver/fuchsia.txt
  libc-test/semver/hermit.txt
  libc-test/semver/linux-aarch64.txt
  libc-test/semver/linux-gnu-loongarch64.txt
  libc-test/semver/linux-gnu-riscv64gc.txt
  libc-test/semver/linux-gnu.txt
  libc-test/semver/linux-loongarch64.txt
  libc-test/semver/linux-riscv64gc.txt
  libc-test/semver/linux.txt
  libc-test/semver/macos-aarch64.txt
  libc-test/semver/netbsd-aarch64.txt
  libc-test/semver/netbsd-mips.txt
  libc-test/semver/netbsd-x86_64.txt
  libc-test/semver/netbsd.txt
  libc-test/semver/openbsd.txt
  libc-test/semver/trusty.txt
  libc-test/semver/unix.txt
  libc-test/semver/wasi-p2.txt
  libc-test/semver/wasi.txt
  libc-test/semver/windows.txt
Labels: S-waiting-on-review

#4017 [0.2] Backports
  libc-test/build.rs
  libc-test/semver/TODO-unix.txt
  libc-test/semver/illumos.txt
  libc-test/semver/unix.txt
  src/unix/mod.rs
  src/unix/solarish/illumos.rs
  src/unix/solarish/mod.rs
  src/unix/solarish/solaris.rs
  src/unix/solarish/x86_64.rs
  src/unix/solarish/x86_common.rs
Labels: S-waiting-on-review

#4006 [0.2] Backports
  libc-test/semver/freebsd-x86_64.txt
  libc-test/semver/freebsd.txt
  src/unix/bsd/freebsdlike/dragonfly/mod.rs
  src/unix/bsd/freebsdlike/freebsd/aarch64.rs
  src/unix/bsd/freebsdlike/freebsd/arm.rs
  src/unix/bsd/freebsdlike/freebsd/freebsd13/mod.rs
  src/unix/bsd/freebsdlike/freebsd/freebsd14/mod.rs
  src/unix/bsd/freebsdlike/freebsd/freebsd15/mod.rs
  src/unix/bsd/freebsdlike/freebsd/mod.rs
  src/unix/bsd/freebsdlike/freebsd/powerpc.rs
  src/unix/bsd/freebsdlike/freebsd/powerpc64.rs
  src/unix/bsd/freebsdlike/freebsd/riscv64.rs
  src/unix/bsd/freebsdlike/freebsd/x86.rs
  src/unix/bsd/freebsdlike/freebsd/x86_64/align.rs
  src/unix/bsd/freebsdlike/freebsd/x86_64/mod.rs
  src/unix/bsd/freebsdlike/mod.rs
  src/unix/linux_like/android/b64/aarch64/align.rs
Labels: S-waiting-on-review

#4020 [0.2] Backports
  libc-test/build.rs
  libc-test/semver/freebsd.txt
  libc-test/semver/linux-gnu.txt
  libc-test/semver/linux.txt
  src/unix/bsd/freebsdlike/freebsd/arm.rs
  src/unix/bsd/freebsdlike/freebsd/mod.rs
  src/unix/linux_like/linux/arch/generic/mod.rs
  src/unix/linux_like/linux/arch/mips/mod.rs
  src/unix/linux_like/linux/arch/powerpc/mod.rs
  src/unix/linux_like/linux/arch/sparc/mod.rs
  src/unix/linux_like/linux/gnu/mod.rs
  src/unix/linux_like/linux/mod.rs
Labels: S-waiting-on-review

#4025 [0.2] Backport: hurd: Use more standard types
  src/unix/hurd/mod.rs
Labels: S-waiting-on-review

#3997 Add i686-unknown-freebsd to CI
  .cirrus.yml
Labels: S-waiting-on-author, stable-nominated

#4026 Ensure that calls to `sort` do not depend on locale
  ci/style.sh
Labels: stable-nominated

#4029 hurd: cleanups
  src/unix/hurd/align.rs
  src/unix/hurd/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3934 Add `get_hostname` to esp-idf
  libc-test/semver/espidf.txt
  src/unix/newlib/espidf/mod.rs
Labels: S-waiting-on-review, stable-nominated

#4032 [0.2] Backports
  .cirrus.yml
  ci/style.sh
  libc-test/semver/apple.txt
  libc-test/semver/linux-gnu.txt
  libc-test/semver/linux-musl.txt
  libc-test/semver/linux.txt
  libc-test/semver/unix.txt
  src/unix/bsd/apple/mod.rs
  src/unix/hurd/align.rs
  src/unix/hurd/mod.rs
  src/unix/linux_like/linux/gnu/mod.rs
  src/unix/linux_like/linux/mod.rs
  src/unix/linux_like/linux/musl/mod.rs
  src/unix/mod.rs
Labels: S-waiting-on-review

#3499 Add group calls to android
  libc-test/build.rs
  libc-test/semver/android.txt
  src/unix/linux_like/android/mod.rs
Labels: S-waiting-on-author, stable-nominated

#4036 triagebot: Set up autolabel and review labels
  triagebot.toml
Labels: S-waiting-on-review, stable-nominated

#3962 emscripten: Upgrade emsdk to 3.1.68
  ci/emscripten.sh
  libc-test/build.rs
  src/unix/linux_like/emscripten/align.rs
  src/unix/linux_like/emscripten/mod.rs
Labels: S-waiting-on-review, O-unix, stable-nominated

#3944 Solarish: add the arc4random* API family
  libc-test/semver/solarish.txt
  src/unix/solarish/mod.rs
Labels: S-waiting-on-review, O-unix, O-solarish, stable-nominated

#4037 triagebot: Don't label everything as O-wasm
  triagebot.toml
Labels: S-waiting-on-review, stable-nominated

#4028 musl: add more syscall constants
  src/unix/linux_like/linux/musl/b64/aarch64/mod.rs
  src/unix/linux_like/linux/musl/b64/powerpc64.rs
  src/unix/linux_like/linux/musl/b64/riscv64/mod.rs
  src/unix/linux_like/linux/musl/b64/s390x.rs
  src/unix/linux_like/linux/musl/b64/x86_64/mod.rs
Labels: S-waiting-on-review

#4022 Add missing sysctl net types for mac
  libc-test/build.rs
  src/unix/bsd/apple/mod.rs
Labels: S-waiting-on-author, O-unix, O-macos, stable-blocked

#4038 Use `#[derive]` for `Copy`/`Clone` in `s!` and friends
  libc-test/build.rs
  src/macros.rs
Labels: S-waiting-on-review, stable-blocked

#4044 AIX: dlopen flags for RTLD_MEMBER and RTLD_NOAUTODEFER
  src/unix/aix/mod.rs
Labels: S-waiting-on-review, O-unix, stable-nominated

#4047 Add the TCP_FUNCTION_BLK and TCP_FUNCTION_ALIAS socket options
  libc-test/build.rs
  libc-test/semver/freebsd.txt
  src/unix/bsd/freebsdlike/freebsd/mod.rs
Labels: S-waiting-on-review, O-unix, stable-nominated

#4041 [0.2] Specify `rust-version = "1.19"` in Cargo.toml
  Cargo.toml
Labels: S-waiting-on-review

#4039 [0.2] Backports
  ci/emscripten.sh
  libc-test/build.rs
  libc-test/semver/android.txt
  libc-test/semver/espidf.txt
  src/unix/linux_like/android/mod.rs
  src/unix/linux_like/emscripten/align.rs
  src/unix/linux_like/emscripten/mod.rs
  src/unix/newlib/espidf/mod.rs
  triagebot.toml
Labels: S-waiting-on-review, O-unix, O-android, O-newlib

#4042 ci: make scripts more uniform
  .github/workflows/full_ci.yml
  ci/android-install-ndk.sh
  ci/android-install-sdk.sh
  ci/build.sh
  ci/docker/wasm32-unknown-emscripten/node-wrapper.sh
  ci/emscripten.sh
  ci/install-musl.sh
  ci/install-rust.sh
  ci/run-docker.sh
  ci/run.sh
  ci/style.sh
  ci/test-runner-linux
  ci/wasi.sh
Labels: S-waiting-on-review, stable-blocked

#4033 feat: add `aio` for solarish
  libc-test/build.rs
  libc-test/semver/solarish.txt
  src/unix/solarish/illumos.rs
  src/unix/solarish/mod.rs
  src/unix/solarish/solaris.rs
Labels: S-waiting-on-review, O-unix, O-wasm, O-solarish, O-illumos, stable-nominated

#4035 Solaris: Add CI, fix: confstr, uc_lwpid is missing from Solaris 11.4 …
  .github/workflows/full_ci.yml
  src/unix/mod.rs
  src/unix/solarish/x86_64.rs
Labels: S-waiting-on-review, O-unix, O-solarish, O-x86, stable-nominated

#4048 [0.2] Backports
  .github/workflows/full_ci.yml
  libc-test/build.rs
  libc-test/semver/freebsd.txt
  libc-test/semver/solarish.txt
  src/unix/aix/mod.rs
  src/unix/bsd/freebsdlike/freebsd/mod.rs
  src/unix/mod.rs
  src/unix/solarish/illumos.rs
  src/unix/solarish/mod.rs
  src/unix/solarish/solaris.rs
  src/unix/solarish/x86_64.rs
Labels: S-waiting-on-review, O-unix, O-solarish, O-illumos, O-x86

#4050 ci: trim trailing whitespace
  .github/workflows/full_ci.yml
Labels: S-waiting-on-review, stable-nominated

#4040 [0.2] Document the MSRV of the stable channel as 1.63
  README.md
Labels: S-waiting-on-review

#4049 [0.2] Set `rust-version` to 1.63
  Cargo.toml
Labels: S-waiting-on-review

#4051 [0.2] ci: Remove tests with rust < 1.63
  .github/workflows/full_ci.yml
  .github/workflows/main.yml
  src/unix/bsd/apple/mod.rs
Labels: S-waiting-on-review, O-unix, O-macos

#4052 triagebot: Add an autolabel for CI
  triagebot.toml
Labels: S-waiting-on-review, stable-nominated

#4053 [0.2] Require rust >= 1.15 and drop libc_priv_mod_use conditional
  build.rs
  libc-test/build.rs
  src/lib.rs
Labels: S-waiting-on-review

#4058 [0.2] Explicitly set the edition to 2015
  Cargo.toml
Labels: S-waiting-on-review

#4056 [0.2] Require rust >= 1.24 and drop libc_const_size_of conditional
  build.rs
  libc-test/build.rs
  src/macros.rs
  src/unix/aix/mod.rs
  src/unix/aix/powerpc64.rs
  src/unix/bsd/apple/mod.rs
  src/unix/bsd/freebsdlike/freebsd/aarch64.rs
  src/unix/bsd/freebsdlike/freebsd/arm.rs
  src/unix/bsd/freebsdlike/freebsd/mod.rs
  src/unix/bsd/freebsdlike/freebsd/powerpc.rs
  src/unix/bsd/freebsdlike/freebsd/powerpc64.rs
  src/unix/bsd/freebsdlike/freebsd/riscv64.rs
  src/unix/bsd/freebsdlike/freebsd/x86.rs
  src/unix/bsd/freebsdlike/freebsd/x86_64/mod.rs
  src/unix/bsd/freebsdlike/mod.rs
  src/unix/bsd/netbsdlike/netbsd/aarch64.rs
  src/unix/bsd/netbsdlike/netbsd/arm.rs
  src/unix/bsd/netbsdlike/netbsd/mips.rs
  src/unix/bsd/netbsdlike/netbsd/mod.rs
  src/unix/bsd/netbsdlike/netbsd/powerpc.rs
  src/unix/bsd/netbsdlike/netbsd/riscv64.rs
  src/unix/bsd/netbsdlike/netbsd/x86.rs
  src/unix/bsd/netbsdlike/netbsd/x86_64.rs
  src/unix/bsd/netbsdlike/openbsd/aarch64.rs
  src/unix/bsd/netbsdlike/openbsd/arm.rs
  src/unix/bsd/netbsdlike/openbsd/mod.rs
  src/unix/bsd/netbsdlike/openbsd/powerpc.rs
  src/unix/bsd/netbsdlike/openbsd/powerpc64.rs
  src/unix/bsd/netbsdlike/openbsd/riscv64.rs
  src/unix/bsd/netbsdlike/openbsd/x86.rs
  src/unix/bsd/netbsdlike/openbsd/x86_64.rs
  src/unix/haiku/native.rs
  src/unix/linux_like/android/b32/arm.rs
  src/unix/linux_like/android/b32/x86/mod.rs
  src/unix/linux_like/android/b64/x86_64/mod.rs
  src/unix/linux_like/android/mod.rs
  src/unix/linux_like/linux/gnu/mod.rs
  src/unix/linux_like/linux/mod.rs
  src/unix/linux_like/linux/musl/mod.rs
  src/unix/nto/x86_64.rs
  src/unix/solarish/mod.rs
  src/unix/solarish/x86_64.rs
Labels: S-waiting-on-review, O-linux, O-unix, O-macos, O-arm, O-musl, O-android, O-mips, O-solarish, O-riscv, O-gnu, O-x86

#4060 [0.2] Remove more outdated configuration
  build.rs
  libc-test/build.rs
  src/fixed_width_ints.rs
  src/fuchsia/mod.rs
  src/hermit.rs
  src/lib.rs
  src/psp.rs
  src/sgx.rs
  src/solid/mod.rs
  src/switch.rs
  src/unix/bsd/apple/b64/aarch64/mod.rs
  src/unix/bsd/apple/mod.rs
  src/unix/linux_like/android/b64/aarch64/int128.rs
  src/unix/linux_like/android/b64/aarch64/mod.rs
  src/unix/linux_like/linux/gnu/b64/aarch64/fallback.rs
  src/unix/linux_like/linux/gnu/b64/aarch64/int128.rs
  src/unix/linux_like/linux/gnu/b64/aarch64/mod.rs
  src/unix/linux_like/linux/mod.rs
  src/unix/linux_like/linux/musl/b64/aarch64/int128.rs
  src/unix/linux_like/linux/musl/b64/aarch64/mod.rs
  src/unix/linux_like/linux/non_exhaustive.rs
  src/unix/mod.rs
  src/unix/newlib/mod.rs
  src/unix/solarish/illumos.rs
  src/vxworks/mod.rs
  src/wasi/mod.rs
  src/windows/mod.rs
  src/xous.rs
Labels: S-waiting-on-review, O-windows, O-linux, O-unix, O-macos, O-arm, O-musl, O-android, O-mips, O-sparc, O-solarish, O-illumos, O-riscv, O-wasi, O-newlib, O-gnu, O-x86

#4062 [0.2] Remove array size hacks for Rust < 1.47
  libc-test/build.rs
  src/unix/bsd/apple/mod.rs
  src/unix/bsd/freebsdlike/dragonfly/mod.rs
  src/unix/bsd/freebsdlike/freebsd/freebsd11/mod.rs
  src/unix/bsd/freebsdlike/freebsd/freebsd12/mod.rs
  src/unix/bsd/freebsdlike/freebsd/freebsd13/mod.rs
  src/unix/bsd/freebsdlike/freebsd/freebsd14/mod.rs
  src/unix/bsd/freebsdlike/freebsd/freebsd15/mod.rs
  src/unix/bsd/freebsdlike/freebsd/mod.rs
  src/unix/bsd/freebsdlike/mod.rs
  src/unix/bsd/netbsdlike/netbsd/mod.rs
  src/unix/linux_like/android/b64/aarch64/mod.rs
  src/unix/linux_like/android/mod.rs
  src/unix/linux_like/linux/gnu/b64/aarch64/mod.rs
  src/unix/linux_like/linux/musl/b64/aarch64/mod.rs
Labels: S-waiting-on-review, O-linux, O-unix, O-macos, O-musl, O-android, O-dragonfly, O-gnu

#4066 Format all markdown files to rewrap text
  README.md
  ci/README.md
  libc-test/semver/README.md
Labels: S-waiting-on-review

#4065 Drop the `ptr_addr_of` conditional
  build.rs
  src/macros.rs
  src/wasi/mod.rs
Labels: S-waiting-on-review, O-wasi

#4068 ci: Remove the logic to handle old rust versions
  ci/build.sh
Labels: S-waiting-on-review, stable-nominated

#4069 [0.2] Backports
  libc-test/Cargo.toml
  libc-test/build.rs
  src/unix/bsd/apple/mod.rs
  triagebot.toml
Labels: S-waiting-on-review, O-unix, O-macos

#4071 Sync docs from 0.2 to main
  CONTRIBUTING.md
  README.md
Labels: S-waiting-on-review, stable-nominated

#4072 [0.2] Make macros.rs more similar to what is on `main`
  src/macros.rs
Labels: S-waiting-on-review

#4073 [0.2] Backports
  CONTRIBUTING.md
  README.md
  src/teeos/mod.rs
  src/unix/haiku/native.rs
Labels: S-waiting-on-review, O-unix

#4074 [0.2] Eliminate uses of `struct_formatter`
  src/unix/aix/powerpc64.rs
  src/unix/bsd/freebsdlike/freebsd/mod.rs
Labels: S-waiting-on-review, O-unix

#4076 [0.2] dragonfly: Add a note for items that differ between the branches
  src/unix/bsd/freebsdlike/dragonfly/errno.rs
  src/unix/bsd/freebsdlike/dragonfly/mod.rs
Labels: S-waiting-on-review, O-unix, O-dragonfly

#4077 netbsd: Cleanup to make the module more similar to `libc-0.2`
  src/unix/bsd/apple/mod.rs
  src/unix/bsd/netbsdlike/netbsd/mod.rs
  src/unix/bsd/netbsdlike/openbsd/mod.rs
Labels: S-waiting-on-review, O-unix, O-macos

#4078 [0.2] Add diff indicators for POSIX_SPAWN_* type change
  src/unix/aix/mod.rs
  src/unix/bsd/apple/mod.rs
  src/unix/bsd/freebsdlike/freebsd/mod.rs
  src/unix/bsd/netbsdlike/mod.rs
  src/unix/haiku/mod.rs
  src/unix/linux_like/linux/mod.rs
  src/unix/nto/mod.rs
Labels: S-waiting-on-review, O-linux, O-unix, O-macos

#4079 [0.2] android: add missing syscall constants
  libc-test/semver/android-aarch64.txt
  libc-test/semver/android-x86_64.txt
  libc-test/semver/android.txt
  src/unix/linux_like/android/b32/arm.rs
  src/unix/linux_like/android/b32/x86/mod.rs
  src/unix/linux_like/android/b64/aarch64/mod.rs
  src/unix/linux_like/android/b64/riscv64/mod.rs
  src/unix/linux_like/android/b64/x86_64/mod.rs
Labels: S-waiting-on-review, O-unix, O-arm, O-android, O-riscv, O-x86

#4075 Eliminate uses of `struct_formatter`
  src/unix/aix/mod.rs
  src/unix/aix/powerpc64.rs
  src/unix/bsd/freebsdlike/freebsd/mod.rs
Labels: S-waiting-on-review, O-unix

#4083 [0.2] triagebot: Sync config with `main`
  triagebot.toml
Labels: S-waiting-on-review

#4081 [0.2] Add more diff notes
  src/fuchsia/mod.rs
  src/unix/aix/mod.rs
  src/unix/bsd/freebsdlike/mod.rs
  src/unix/bsd/netbsdlike/mod.rs
  src/unix/haiku/mod.rs
  src/unix/hurd/mod.rs
  src/unix/linux_like/linux/gnu/mod.rs
  src/unix/linux_like/mod.rs
  src/unix/mod.rs
  src/unix/newlib/mod.rs
  src/unix/nto/mod.rs
  src/unix/solarish/solaris.rs
  src/windows/mod.rs
Labels: S-waiting-on-review, O-windows, O-linux, O-unix, O-solarish, O-linux-like, O-newlib, O-gnu

#4082 [0.2] Backports
  libc-test/semver/linux-gnu.txt
  libc-test/semver/redox.txt
  libc-test/semver/windows.txt
  src/unix/linux_like/linux/gnu/b32/arm/mod.rs
  src/unix/linux_like/linux/gnu/b32/mips/mod.rs
  src/unix/linux_like/linux/gnu/b32/powerpc.rs
  src/unix/linux_like/linux/gnu/b32/x86/mod.rs
  src/unix/linux_like/linux/gnu/mod.rs
  src/unix/linux_like/linux/musl/b64/aarch64/mod.rs
  src/unix/linux_like/linux/musl/b64/powerpc64.rs
  src/unix/linux_like/linux/musl/b64/riscv64/mod.rs
  src/unix/linux_like/linux/musl/b64/s390x.rs
  src/unix/linux_like/linux/musl/b64/x86_64/mod.rs
  src/unix/redox/mod.rs
  src/windows/mod.rs
Labels: S-waiting-on-review, O-windows, O-linux, O-unix, O-arm, O-musl, O-mips, O-redox, O-riscv, O-gnu, O-x86

#4084 Sync Cargo.toml and changelog from `libc-0.2`
  CHANGELOG.md
  Cargo.toml
  libc-test/Cargo.toml
Labels: S-waiting-on-review

#4063 [0.2] Drop the `libc_const_extern_fn` conditional
  Cargo.toml
  README.md
  build.rs
  src/lib.rs
  src/macros.rs
  src/unix/bsd/apple/mod.rs
  src/unix/bsd/freebsdlike/freebsd/mod.rs
  src/unix/bsd/netbsdlike/netbsd/mod.rs
  tests/const_fn.rs
Labels: S-waiting-on-review, O-unix, O-macos

#4064 [0.2] Require rust >= 1.37 and drop libc_underscore_const_names conditional
  build.rs
  src/fixed_width_ints.rs
Labels: S-waiting-on-review

#4087 Add a check that semver files don't contain duplicate entries
  ci/style.sh
Labels: S-waiting-on-review, stable-nominated

#4086 [0.2] Small sync fixes and backports
  build.rs
  ci/README.md
  ci/style.sh
  libc-test/build.rs
  libc-test/semver/TODO-linux.txt
  libc-test/semver/android.txt
  libc-test/semver/apple.txt
  libc-test/semver/freebsd.txt
  libc-test/semver/linux-aarch64.txt
  libc-test/semver/linux-i686.txt
  libc-test/semver/linux-musl.txt
  libc-test/semver/linux-powerpc64.txt
  libc-test/semver/linux-riscv64gc.txt
  libc-test/semver/linux-x86_64.txt
  libc-test/semver/linux.txt
  src/unix/bsd/apple/mod.rs
  src/unix/bsd/freebsdlike/freebsd/mod.rs
  src/unix/linux_like/android/mod.rs
  src/unix/linux_like/linux/mod.rs
  src/unix/linux_like/linux/musl/mod.rs
Labels: S-waiting-on-review, O-linux, O-unix, O-macos, O-musl, O-android

#4091 [0.2] Backports
  libc-test/build.rs
  libc-test/semver/android.txt
  libc-test/semver/unix.txt
  src/fuchsia/mod.rs
  src/lib.rs
  src/macros.rs
  src/unix/aix/mod.rs
  src/unix/aix/powerpc64.rs
  src/unix/bsd/apple/mod.rs
  src/unix/bsd/mod.rs
  src/unix/bsd/netbsdlike/netbsd/aarch64.rs
  src/unix/linux_like/android/b32/mod.rs
  src/unix/linux_like/android/b64/aarch64/mod.rs
  src/unix/linux_like/android/b64/riscv64/mod.rs
  src/unix/linux_like/android/b64/x86_64/mod.rs
  src/unix/linux_like/android/mod.rs
  src/unix/linux_like/mod.rs
  src/unix/mod.rs
  src/unix/newlib/mod.rs
  src/unix/nto/mod.rs
  src/unix/redox/mod.rs
  src/unix/solarish/mod.rs
Labels: S-waiting-on-review, O-unix, O-bsd, O-macos, O-android, O-solarish, O-redox, O-riscv, O-linux-like, O-newlib, O-x86

#4093 Sync more files with `main` to reduce the diff
  src/unix/bsd/apple/mod.rs
  src/unix/bsd/freebsdlike/freebsd/x86.rs
  src/unix/bsd/netbsdlike/openbsd/mod.rs
  src/unix/linux_like/linux/mod.rs
  src/unix/mod.rs
  src/wasi/mod.rs
Labels: S-waiting-on-review, O-linux, O-unix, O-macos, O-wasi, O-x86

#4094 Sync more files with `libc-0.2` to reduce the diff
  src/fixed_width_ints.rs
  src/macros.rs
  src/unix/bsd/apple/b64/aarch64/mod.rs
  src/unix/bsd/apple/mod.rs
  src/unix/bsd/freebsdlike/freebsd/arm.rs
  src/unix/bsd/freebsdlike/freebsd/mod.rs
  src/unix/bsd/freebsdlike/freebsd/powerpc.rs
  src/unix/bsd/freebsdlike/freebsd/powerpc64.rs
  src/unix/bsd/freebsdlike/freebsd/riscv64.rs
  src/unix/bsd/netbsdlike/openbsd/mod.rs
  src/unix/haiku/native.rs
  src/unix/linux_like/android/b32/arm.rs
  src/unix/linux_like/android/mod.rs
  src/unix/linux_like/linux/mod.rs
  src/unix/mod.rs
  src/wasi/mod.rs
Labels: S-waiting-on-review, O-linux, O-unix, O-macos, O-arm, O-android, O-riscv, O-wasi

#4089 hurd: Add domainname field to utsname
  src/unix/hurd/mod.rs
Labels: S-waiting-on-review, O-unix, stable-nominated

#4088 openbsd: skip ATF_* constants in CI
  libc-test/build.rs
Labels: S-waiting-on-review, stable-nominated

#4096 [0.2] Remove the `long_array` conditional
  build.rs
  src/unix/bsd/apple/long_array.rs
  src/unix/bsd/apple/mod.rs
Labels: S-waiting-on-review, O-unix, O-macos

#4097 [0.2] Update `mach`-related deprecation notices
  src/unix/bsd/apple/mod.rs
Labels: S-waiting-on-review, O-unix, O-macos

#4099 [0.2] Sync `libc-test/build.rs` with `main` where possible
  libc-test/build.rs
Labels: S-waiting-on-review

#4101 [0.2] Backports
  src/unix/aix/mod.rs
  src/unix/bsd/apple/mod.rs
  src/unix/bsd/mod.rs
Labels: S-waiting-on-review, O-unix, O-bsd, O-macos

#4103 Solaris: add definition for _POSIX_VDISABLE
  libc-test/semver/solarish.txt
  src/unix/solarish/mod.rs
Labels: S-waiting-on-review, O-unix, O-solarish, stable-nominated

#4104 [main] Remove the `long_array` conditional
  src/unix/bsd/apple/long_array.rs
  src/unix/bsd/apple/mod.rs
Labels: S-waiting-on-review, O-unix, O-macos

#4095 [0.2] apple: Mark mach_task_self as deprecated
  src/unix/bsd/apple/mod.rs
Labels: S-waiting-on-review, O-unix, O-macos

#4105 [main] Drop the `libc_const_extern_fn` conditional
  Cargo.toml
  README.md
  build.rs
Labels: S-waiting-on-review

#4108 Set `-u` (error on unset) in all script files
  ci/android-install-ndk.sh
  ci/android-install-sdk.sh
  ci/android-sysimage.sh
  ci/build.sh
  ci/docker/wasm32-unknown-emscripten/node-wrapper.sh
  ci/emscripten-entry.sh
  ci/emscripten.sh
  ci/install-musl.sh
  ci/install-rust.sh
  ci/linux-s390x.sh
  ci/linux-sparc64.sh
  ci/run-docker.sh
  ci/run.sh
  ci/style.sh
  ci/test-runner-linux
  ci/wasi.sh
Labels: S-waiting-on-review

#4092 ci: add support for loongarch64-unknown-linux-musl
  .github/workflows/full_ci.yml
  ci/docker/loongarch64-unknown-linux-musl/Dockerfile
  ci/install-musl-cross.sh
  libc-test/build.rs
  libc-test/semver/linux-gnu-loongarch64.txt
  libc-test/semver/linux-loongarch64.txt
  src/unix/linux_like/linux/arch/generic/mod.rs
  src/unix/linux_like/linux/musl/b64/loongarch64/mod.rs
  src/unix/linux_like/linux/musl/mod.rs
Labels: A-CI, S-waiting-on-review, O-linux, O-unix, O-musl, stable-nominated

#4111 [0.2] Backports
  .github/workflows/full_ci.yml
  ci/android-install-ndk.sh
  ci/android-install-sdk.sh
  ci/android-sysimage.sh
  ci/build.sh
  ci/docker/loongarch64-unknown-linux-musl/Dockerfile
  ci/docker/wasm32-unknown-emscripten/node-wrapper.sh
  ci/emscripten-entry.sh
  ci/emscripten.sh
  ci/install-musl-cross.sh
  ci/install-musl.sh
  ci/install-rust.sh
  ci/linux-s390x.sh
  ci/linux-sparc64.sh
  ci/run-docker.sh
  ci/run.sh
  ci/style.sh
  ci/test-runner-linux
  ci/wasi.sh
  libc-test/build.rs
  libc-test/semver/linux-gnu-loongarch64.txt
  libc-test/semver/linux-loongarch64.txt
  libc-test/semver/solarish.txt
  src/unix/hurd/mod.rs
  src/unix/linux_like/linux/arch/generic/mod.rs
  src/unix/linux_like/linux/musl/b64/loongarch64/mod.rs
  src/unix/linux_like/linux/musl/mod.rs
  src/unix/solarish/mod.rs
Labels: A-CI, S-waiting-on-review, O-linux, O-unix, O-musl, O-solarish

#3468 netbsd adding mcontext related data for riscv64
  src/unix/bsd/netbsdlike/netbsd/riscv64.rs
Labels: S-waiting-on-review, O-unix, O-riscv, stable-nominated

#4123 [0.2] ci: Update or patch Docker images
  ci/docker/aarch64-linux-android/Dockerfile
  ci/docker/aarch64-unknown-linux-gnu/Dockerfile
  ci/docker/aarch64-unknown-linux-musl/Dockerfile
  ci/docker/arm-linux-androideabi/Dockerfile
  ci/docker/arm-unknown-linux-gnueabihf/Dockerfile
  ci/docker/arm-unknown-linux-musleabihf/Dockerfile
  ci/docker/armv7-unknown-linux-uclibceabihf/Dockerfile
  ci/docker/asmjs-unknown-emscripten/Dockerfile
  ci/docker/i686-linux-android/Dockerfile
  ci/docker/i686-unknown-linux-gnu/Dockerfile
  ci/docker/i686-unknown-linux-musl/Dockerfile
  ci/docker/loongarch64-unknown-linux-gnu/Dockerfile
  ci/docker/loongarch64-unknown-linux-musl/Dockerfile
  ci/docker/powerpc-unknown-linux-gnu/Dockerfile
  ci/docker/powerpc64-unknown-linux-gnu/Dockerfile
  ci/docker/powerpc64le-unknown-linux-gnu/Dockerfile
  ci/docker/riscv64gc-unknown-linux-gnu/Dockerfile
  ci/docker/s390x-unknown-linux-gnu/Dockerfile
  ci/docker/s390x-unknown-linux-musl/Dockerfile
  ci/docker/sparc64-unknown-linux-gnu/Dockerfile
  ci/docker/wasm32-unknown-emscripten/Dockerfile
  ci/docker/wasm32-wasip1/Dockerfile
  ci/docker/wasm32-wasip2/Dockerfile
  ci/docker/x86_64-linux-android/Dockerfile
  ci/docker/x86_64-unknown-linux-gnu/Dockerfile
  ci/docker/x86_64-unknown-linux-gnux32/Dockerfile
  ci/docker/x86_64-unknown-linux-musl/Dockerfile
  ci/style.sh
  libc-test/build.rs
  src/macros.rs
Labels: S-waiting-on-review

#4120 ci: Update or patch Docker images
  ci/docker/aarch64-linux-android/Dockerfile
  ci/docker/aarch64-unknown-linux-gnu/Dockerfile
  ci/docker/aarch64-unknown-linux-musl/Dockerfile
  ci/docker/arm-linux-androideabi/Dockerfile
  ci/docker/arm-unknown-linux-gnueabihf/Dockerfile
  ci/docker/arm-unknown-linux-musleabihf/Dockerfile
  ci/docker/armv7-unknown-linux-uclibceabihf/Dockerfile
  ci/docker/asmjs-unknown-emscripten/Dockerfile
  ci/docker/i686-linux-android/Dockerfile
  ci/docker/i686-unknown-linux-gnu/Dockerfile
  ci/docker/i686-unknown-linux-musl/Dockerfile
  ci/docker/loongarch64-unknown-linux-gnu/Dockerfile
  ci/docker/loongarch64-unknown-linux-musl/Dockerfile
  ci/docker/powerpc-unknown-linux-gnu/Dockerfile
  ci/docker/powerpc64-unknown-linux-gnu/Dockerfile
  ci/docker/powerpc64le-unknown-linux-gnu/Dockerfile
  ci/docker/riscv64gc-unknown-linux-gnu/Dockerfile
  ci/docker/s390x-unknown-linux-gnu/Dockerfile
  ci/docker/s390x-unknown-linux-musl/Dockerfile
  ci/docker/sparc64-unknown-linux-gnu/Dockerfile
  ci/docker/wasm32-unknown-emscripten/Dockerfile
  ci/docker/wasm32-wasip1/Dockerfile
  ci/docker/wasm32-wasip2/Dockerfile
  ci/docker/x86_64-linux-android/Dockerfile
  ci/docker/x86_64-unknown-linux-gnu/Dockerfile
  ci/docker/x86_64-unknown-linux-gnux32/Dockerfile
  ci/docker/x86_64-unknown-linux-musl/Dockerfile
  ci/style.sh
  libc-test/build.rs
  src/macros.rs
Labels: A-CI, S-waiting-on-review, stable-nominated

#3601 Support mkostemp, mkostemps on Android
  src/unix/linux_like/emscripten/mod.rs
  src/unix/linux_like/linux/mod.rs
  src/unix/linux_like/mod.rs
Labels: S-waiting-on-author, O-linux, O-unix, O-linux-like, stable-nominated, S-waiting-on-ci

#3211 uclibc/mips: fixed SA_* mismatched types
  src/unix/linux_like/linux/uclibc/mips/mod.rs
Labels: O-linux, O-unix, O-mips, stable-nominated, S-waiting-on-ci

#4113 add various `ptp_*` structs
  libc-test/build.rs
  libc-test/semver/linux.txt
  src/unix/linux_like/linux/mod.rs
Labels: O-linux, O-unix, stable-nominated, S-waiting-on-ci

#4125 ci: Ensure build channels get run even if FILTER is unset
  ci/build.sh
Labels: S-waiting-on-review, stable-nominated

#4114 add various `PTP_` consts
  libc-test/build.rs
  libc-test/semver/linux.txt
  src/unix/linux_like/linux/mod.rs
Labels: S-waiting-on-review, O-linux, O-unix, stable-nominated

#1833 FreeBSDLike: Remove obsolete constants in version 1.0.0
  libc-test/build.rs
  src/unix/bsd/freebsdlike/freebsd/mod.rs
Labels: breakage-candidate, S-waiting-on-author, O-unix, stable-declined, S-waiting-on-ci

#4127 hurd: Update mmap flags
  src/unix/hurd/mod.rs
Labels: S-waiting-on-review, O-unix, stable-nominated

#4129 Fix the tests on riscv64gc-unknown-freebsd
  src/unix/bsd/freebsdlike/freebsd/riscv64.rs
Labels: S-waiting-on-review, O-unix, O-riscv, stable-nominated

#3625 Windows `stats::st_mode` and `stat` flags type.
  src/windows/mod.rs
Labels: breakage-candidate, S-waiting-on-author, O-windows, stable-declined

#2406 Raise libc's FreeBSD ABI to 12
  build.rs
Labels: S-waiting-on-author

#3921 ci: update musl headers to 6.6
  ci/docker/aarch64-unknown-linux-musl/Dockerfile
  ci/docker/arm-unknown-linux-musleabihf/Dockerfile
  ci/docker/i686-unknown-linux-musl/Dockerfile
  ci/docker/s390x-unknown-linux-musl/Dockerfile
  ci/docker/x86_64-unknown-linux-musl/Dockerfile
  ci/install-musl.sh
  libc-test/build.rs
Labels: S-waiting-on-author, stable-nominated

#4131 [0.2] Backports
  src/unix/bsd/freebsdlike/freebsd/riscv64.rs
  src/unix/bsd/netbsdlike/netbsd/riscv64.rs
  src/unix/hurd/mod.rs
  src/unix/linux_like/linux/uclibc/mips/mod.rs
Labels: S-waiting-on-review, O-linux, O-unix, O-mips, O-riscv

#4128 add `ptp_clock_caps`
  libc-test/build.rs
  libc-test/semver/linux.txt
  src/unix/linux_like/linux/mod.rs
Labels: S-waiting-on-review, O-linux, O-unix, stable-nominated

#4046 Add struct and constants for mount_setattr syscall
  libc-test/semver/linux.txt
  src/unix/linux_like/linux/mod.rs
Labels: S-waiting-on-author, O-linux, O-unix, stable-nominated

#4133 use `qemu-sparc64` to run sparc64 tests
  ci/docker/sparc64-unknown-linux-gnu/Dockerfile
Labels: S-waiting-on-review

#4106 [0.2] Synchronize branches, backport Sparc CI fix
  ci/docker/sparc64-unknown-linux-gnu/Dockerfile
  src/fuchsia/mod.rs
  src/unix/bsd/apple/mod.rs
  src/unix/linux_like/linux/mod.rs
  src/windows/mod.rs
Labels: S-waiting-on-review, O-windows, O-linux, O-unix, O-macos

#4136 style: Allow rustfmt to organize imports
  build.rs
  libc-test/test/cmsg.rs
  rustfmt.toml
  src/lib.rs
  src/unix/linux_like/emscripten/lfs64.rs
  src/unix/linux_like/linux/musl/lfs64.rs
  src/unix/nuttx/mod.rs
  src/unix/solarish/compat.rs
  src/unix/solarish/illumos.rs
  src/unix/solarish/solaris.rs
  src/vxworks/mod.rs
  src/wasi/mod.rs
Labels: S-waiting-on-review, O-linux, O-unix, O-musl, O-solarish, O-illumos, O-wasi, stable-nominated

#3978 linux_like: Unify statx definitions
  src/unix/linux_like/android/mod.rs
  src/unix/linux_like/linux/gnu/mod.rs
  src/unix/linux_like/mod.rs
Labels: S-waiting-on-review, O-linux, O-unix, O-android, O-linux-like, O-gnu, stable-nominated

#4137 apple: remove `if_family_id`
  src/unix/bsd/apple/mod.rs
Labels: S-waiting-on-review, O-unix, O-macos

#3261 Unify definitions of `siginfo_t`, `statvfs` and `statfs` in `musl` targets
  src/unix/linux_like/linux/gnu/b32/riscv32/mod.rs
  src/unix/linux_like/linux/gnu/b32/sparc/mod.rs
  src/unix/linux_like/linux/musl/b32/arm/mod.rs
  src/unix/linux_like/linux/musl/b32/hexagon.rs
  src/unix/linux_like/linux/musl/b32/mips/mod.rs
  src/unix/linux_like/linux/musl/b32/powerpc.rs
  src/unix/linux_like/linux/musl/b32/riscv32/mod.rs
  src/unix/linux_like/linux/musl/b32/x86/mod.rs
  src/unix/linux_like/linux/musl/b64/loongarch64/mod.rs
  src/unix/linux_like/linux/musl/b64/mips64.rs
  src/unix/linux_like/linux/musl/b64/mod.rs
  src/unix/linux_like/linux/musl/b64/riscv64/mod.rs
  src/unix/linux_like/linux/musl/b64/s390x.rs
  src/unix/linux_like/linux/musl/mod.rs
Labels: S-waiting-on-review, O-linux, O-unix, O-arm, O-musl, O-mips, O-sparc, O-riscv, O-gnu, O-x86

#4139 [0.2] Backports
  libc-test/build.rs
  libc-test/semver/linux.txt
  src/unix/linux_like/linux/gnu/mod.rs
  src/unix/linux_like/linux/mod.rs
  src/unix/linux_like/linux/musl/mod.rs
Labels: S-waiting-on-review, O-linux, O-unix, O-macos, O-arm, O-musl, O-android, O-mips, O-sparc, O-solarish, O-illumos, O-riscv, O-linux-like, O-wasi, O-gnu, O-x86

#4134 fix: make sure the `const-extern-fn` feature is enabled
  Cargo.toml
  ci/run.sh
  tests/const_fn.rs
Labels: A-CI, S-waiting-on-review, stable-nominated

#3357 Expose `len8_dlc` field of `can_frame` struct.
  src/unix/linux_like/linux/mod.rs
Labels: S-waiting-on-review, O-linux, O-unix, stable-nominated, S-waiting-on-ci

#4135 [0.2]: fix: make sure the const-extern-fn feature is enabled
  Cargo.toml
  ci/run.sh
Labels: S-waiting-on-review

#4143 [0.2]: Expose `len8_dlc` field of `can_frame` struct.
  src/unix/linux_like/linux/mod.rs
Labels: S-waiting-on-review, O-linux, O-unix

#3630 Fix the definition of sigevent on FreeBSD and Linux
  libc-test/build.rs
  src/unix/bsd/freebsdlike/freebsd/mod.rs
  src/unix/linux_like/linux/gnu/mod.rs
  src/unix/linux_like/linux/musl/mod.rs
  src/unix/linux_like/mod.rs
Labels: breakage-candidate, S-waiting-on-review, O-linux, O-unix, O-musl, O-linux-like, O-gnu, stable-declined, S-waiting-on-ci

#4146 release-plz: Fix the pull request URL
  .release-plz.toml
Labels: S-waiting-on-review

#4150 [0.2] Array size revert
  libc-test/build.rs
  src/unix/bsd/apple/mod.rs
  src/unix/bsd/freebsdlike/dragonfly/mod.rs
  src/unix/bsd/freebsdlike/freebsd/freebsd11/mod.rs
  src/unix/bsd/freebsdlike/freebsd/freebsd12/mod.rs
  src/unix/bsd/freebsdlike/freebsd/freebsd13/mod.rs
  src/unix/bsd/freebsdlike/freebsd/freebsd14/mod.rs
  src/unix/bsd/freebsdlike/freebsd/freebsd15/mod.rs
  src/unix/bsd/freebsdlike/freebsd/mod.rs
  src/unix/bsd/freebsdlike/mod.rs
  src/unix/bsd/netbsdlike/netbsd/mod.rs
Labels: S-waiting-on-review, O-linux, O-unix, O-macos, O-musl, O-android, O-dragonfly, O-gnu

#4151 Ensure all tests in the workspace are run and that `const extern fn` is always enabled
  Cargo.toml
  build.rs
  ci/run.sh
  ci/verify-build.sh
  src/macros.rs
Labels: S-waiting-on-review, stable-nominated

#4152 [0.2]: Ensure all tests in the workspace are run and that const extern fn is always enabled
  Cargo.toml
  build.rs
  ci/run.sh
  src/macros.rs
Labels: S-waiting-on-review

#4154 Add a `.git-blame-ingore-revs` entry for edition 2021 changes
  .git-blame-ignore-revs
Labels: S-waiting-on-review

#4157 fix(wasi): Add back unsafe block for clockid_t static variables
  ci/verify-build.sh
  src/wasi/mod.rs
Labels: A-CI, S-waiting-on-review, O-windows, O-linux, O-unix, O-bsd, O-macos, O-arm, O-musl, O-android, O-mips, O-sparc, O-dragonfly, O-solarish, O-illumos, O-redox, O-riscv, O-linux-like, O-wasi, O-newlib, O-gnu, O-x86, stable-nominated

#4160 [0.2] Backports
  ci/verify-build.sh
  src/wasi/mod.rs
Labels: S-waiting-on-review, O-wasi

#4159 ci: Check various FreeBSD versions
  build.rs
  ci/verify-build.sh
  libc-test/build.rs
  src/unix/bsd/freebsdlike/freebsd/freebsd11/b32.rs
  src/unix/bsd/freebsdlike/freebsd/freebsd11/b64.rs
  src/unix/bsd/freebsdlike/freebsd/freebsd11/mod.rs
Labels: S-waiting-on-review, O-unix, stable-nominated

#4162 Handle remaining leading `::` in paths
  ci/style.rs
  src/fuchsia/mod.rs
  src/teeos/mod.rs
  src/unix/bsd/apple/mod.rs
  src/unix/bsd/netbsdlike/netbsd/riscv64.rs
  src/unix/bsd/netbsdlike/openbsd/arm.rs
  src/unix/linux_like/linux/gnu/b32/m68k/mod.rs
  src/unix/linux_like/linux/gnu/b64/loongarch64/mod.rs
  src/unix/linux_like/linux/gnu/b64/x86_64/not_x32.rs
  src/unix/linux_like/linux/mod.rs
  src/unix/linux_like/linux/musl/b32/riscv32/mod.rs
  src/unix/linux_like/linux/uclibc/mips/mips64/mod.rs
  src/unix/newlib/aarch64/mod.rs
  src/unix/nto/neutrino.rs
  src/unix/redox/mod.rs
  src/unix/solarish/x86.rs
Labels: S-waiting-on-review, O-linux, O-unix, O-macos, O-arm, O-musl, O-mips, O-solarish, O-redox, O-riscv, O-newlib, O-gnu, O-x86, stable-nominated

#4145 solarish update stat type with st_fstype field.
  libc-test/semver/solarish.txt
  src/unix/solarish/mod.rs
Labels: S-waiting-on-review, O-unix, O-solarish, stable-nominated

#4165 Add a `.git-blame-ignore-revs` entry for adding the prelude
  .git-blame-ignore-revs
Labels: S-waiting-on-review

#4163 move AF_XDP structs and constants to `linux/mod.rs`
  libc-test/semver/linux-gnu.txt
  libc-test/semver/linux-musl.txt
  libc-test/semver/linux.txt
  src/unix/linux_like/linux/gnu/mod.rs
  src/unix/linux_like/linux/mod.rs
  src/unix/linux_like/linux/musl/mod.rs
Labels: S-waiting-on-review, O-linux, O-unix, O-musl, O-gnu

#4158 Fix usage with `rustc-dep-of-std`
  ci/verify-build.sh
  src/lib.rs
  src/macros.rs
Labels: S-waiting-on-review, O-windows, O-linux, O-unix, O-bsd, O-macos, O-arm, O-musl, O-android, O-mips, O-sparc, O-dragonfly, O-solarish, O-illumos, O-redox, O-riscv, O-linux-like, O-wasi, O-newlib, O-gnu, O-x86, stable-nominated

#4167 [0.2] Fix usage with `rustc-dep-of-std`
  ci/verify-build.sh
  src/lib.rs
  src/macros.rs
Labels: S-waiting-on-review
