Repository rust-lang/libc, pull requests merged in 2024-08, with the labels that each got.

#3797 Combined CI fixes
  .github/workflows/full_ci.yml
  Cargo.toml
  ci/build.sh
  libc-test/build.rs
  src/fixed_width_ints.rs
  src/unix/bsd/apple/mod.rs
  src/wasi.rs
Labels: S-waiting-on-review, stable-nominated

#3734 feat: add missing netfilter consts
  libc-test/build.rs
  libc-test/semver/android.txt
  libc-test/semver/linux.txt
  src/unix/linux_like/android/mod.rs
  src/unix/linux_like/linux/mod.rs
Labels: S-waiting-on-review

#3616 Move testing of primitive types from std
  libc-test/Cargo.toml
  libc-test/test/primitive_types.rs
Labels: S-waiting-on-review

#3799 Allow setting `stable-nominated` via rustbot
  triagebot.toml
Labels: S-waiting-on-review

#3706 fix: use c_char from crate root
  src/unix/bsd/mod.rs
Labels: S-waiting-on-author

#3780 vxWorks adding few errnoLib related constants.
  src/vxworks/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3802 Update macro docs and formatting
  src/macros.rs
Labels: S-waiting-on-review

#3784 Define SO_BINDTOIFINDEX on Fuchsia
  libc-test/semver/fuchsia.txt
  src/fuchsia/mod.rs
Labels: S-waiting-on-review

#3788 [illumos] add pthread stack functions
  libc-test/semver/illumos.txt
  src/unix/solarish/illumos.rs
Labels: S-waiting-on-review, stable-nominated

#3757 Add clone_args for riscv64 linux gnu/musl
  src/unix/linux_like/linux/gnu/b64/riscv64/align.rs
  src/unix/linux_like/linux/musl/b64/riscv64/align.rs
Labels: S-waiting-on-review

#3804 Update documentation with the 0.2/1.0 workflow
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
Labels: S-waiting-on-review

#3806 [0.2] Combined CI fixes
  .github/workflows/full_ci.yml
  Cargo.toml
  ci/build.sh
  libc-test/build.rs
Labels: S-waiting-on-review

#3801 freebsd moving the kinfo_file type to general use.
  libc-test/semver/freebsd-x86_64.txt
  libc-test/semver/freebsd.txt
  src/unix/bsd/freebsdlike/freebsd/mod.rs
  src/unix/bsd/freebsdlike/freebsd/x86.rs
  src/unix/bsd/freebsdlike/freebsd/x86_64/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3787 Add Futex Constants FUTEX_WAITERS, FUTEX_OWNER_DIED and FUTEX_TID_MASK to Linux
  libc-test/semver/linux.txt
  src/unix/linux_like/linux/mod.rs
Labels: S-waiting-on-author, stable-nominated

#3808 Add a note asking for headers or documentation in PRs
  .github/PULL_REQUEST_TEMPLATE.md
Labels: S-waiting-on-review

#3809 [main] Readd posix_spawn{_file_actions_t,attr_t} on Android
  libc-test/build.rs
  src/unix/linux_like/android/mod.rs
Labels: S-waiting-on-review

#3805 [0.2] vxWorks: add a few errnoLib related constants.
  src/vxworks/mod.rs
Labels: S-waiting-on-review

#3807 [0.2] illumos: add pthread stack functions
  libc-test/semver/illumos.txt
  src/unix/solarish/illumos.rs
Labels: S-waiting-on-review

#3810 [0.2] haiku: add B_APP_IMAGE_SYMBOL definition
  src/unix/haiku/native.rs
Labels: S-waiting-on-review

#3811 [0.2] Add clone_args for riscv64 linux gnu/musl
  src/unix/linux_like/linux/gnu/b64/riscv64/align.rs
  src/unix/linux_like/linux/musl/b64/riscv64/align.rs
Labels: S-waiting-on-review

#3812 [0.2] freebsd moving the kinfo_file type to general use.
  libc-test/semver/freebsd-x86_64.txt
  libc-test/semver/freebsd.txt
  src/unix/bsd/freebsdlike/freebsd/mod.rs
  src/unix/bsd/freebsdlike/freebsd/x86.rs
  src/unix/bsd/freebsdlike/freebsd/x86_64/mod.rs
Labels: S-waiting-on-review

#3645 Fix hidden lifetime parameter
  src/unix/aix/mod.rs
  src/unix/aix/powerpc64.rs
Labels: S-waiting-on-review

#3813 [0.2] add FUTEX_WAITERS, FUTEX_OWNER_DIED and FUTEX_TID_MASK to linux
  libc-test/semver/linux.txt
  src/unix/linux_like/linux/mod.rs
Labels: S-waiting-on-review

#3814 [0.2] Backport hermit
  src/hermit.rs
  src/hermit/aarch64.rs
  src/hermit/mod.rs
  src/hermit/x86_64.rs
Labels: S-waiting-on-review

#3815 Add QNX NTO platform support
  src/unix/linux_like/linux/mod.rs
  src/unix/nto/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3702 Add `_NSGetArgv`, `_NSGetArgc` and `_NSGetProgname` from `crt_externs.h`
  libc-test/semver/apple.txt
  src/unix/bsd/apple/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3816 Add myself to the review rotation
  triagebot.toml
Labels: S-waiting-on-review

#3817 [main] Add SIG constants to espidf
  src/unix/newlib/espidf/mod.rs
Labels: S-waiting-on-review

#3818 [main] Disable libregex for QNX 7.0 #3775
  src/unix/nto/mod.rs
Labels: S-waiting-on-review

#3819 [0.2] Backport confstr api
  libc-test/semver/linux-gnu.txt
  src/unix/linux_like/linux/gnu/mod.rs
Labels: S-waiting-on-review

#3745 freebsd adding execvpe support from 14.1 release
  libc-test/build.rs
  libc-test/semver/freebsd.txt
  src/unix/bsd/freebsdlike/freebsd/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3820 [0.2] Backport of five PRs
  build.rs
  libc-test/semver/android.txt
  libc-test/semver/solarish.txt
  src/unix/haiku/mod.rs
  src/unix/linux_like/android/mod.rs
  src/unix/mod.rs
  src/unix/solarish/mod.rs
Labels: S-waiting-on-review

#3821 [0.2] Backport of four PRs
  src/unix/hurd/mod.rs
  src/unix/linux_like/linux/mod.rs
  src/unix/nto/mod.rs
  src/unix/solarish/mod.rs
  src/vxworks/mod.rs
Labels: S-waiting-on-review

#3563 Add fcntl OFD commands for macOS
  libc-test/semver/apple.txt
  src/unix/bsd/apple/mod.rs
Labels: S-waiting-on-author, stable-nominated

#3773 add `pthread_equal`
  libc-test/semver/unix.txt
  src/unix/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3717 Add missing networking support for Illumos/Solaris as used in quinn
  libc-test/semver/solarish.txt
  src/unix/mod.rs
  src/unix/solarish/mod.rs
Labels: S-waiting-on-author, stable-nominated

#3721 netbsd adding _lwp_park api.
  libc-test/semver/netbsd.txt
  src/unix/bsd/netbsdlike/netbsd/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3777 Add `klogctl` to linux and android
  libc-test/build.rs
  libc-test/semver/android.txt
  libc-test/semver/linux.txt
  src/unix/linux_like/android/mod.rs
  src/unix/linux_like/linux/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3823 Add `release-plz` for the 0.2 branch
  .github/workflows/publish_0.2.yml
  .release-plz.toml
  libc-test/Cargo.toml
Labels: S-waiting-on-review

#3825 Enable publishing new versions via release-plz
  .github/workflows/publish_0.2.yml
  .release-plz.toml
Labels: S-waiting-on-review

#3722 Unify the ioctl declarations on linux
  src/unix/linux_like/linux/gnu/mod.rs
  src/unix/linux_like/linux/mod.rs
  src/unix/linux_like/linux/musl/mod.rs
  src/unix/linux_like/linux/uclibc/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3822 openbsd/netbsd commonize getnameinfo
  src/unix/bsd/netbsdlike/mod.rs
  src/unix/bsd/netbsdlike/netbsd/mod.rs
  src/unix/bsd/netbsdlike/openbsd/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3681 Add wasi select, FD_SET, FD_ZERO, FD_ISSET
  libc-test/semver/wasi.txt
  src/wasi.rs
Labels: S-waiting-on-review, stable-nominated

#3827 Backport beetroot
  libc-test/semver/apple.txt
  libc-test/semver/wasi.txt
  src/unix/bsd/apple/mod.rs
  src/unix/bsd/netbsdlike/mod.rs
  src/unix/bsd/netbsdlike/netbsd/mod.rs
  src/unix/bsd/netbsdlike/openbsd/mod.rs
  src/wasi.rs
Labels: S-waiting-on-review

#3828 Update CHANGELOG.md
  CHANGELOG.md
Labels: S-waiting-on-review

#3829 Use the same tag and release names
  .release-plz.toml
Labels: S-waiting-on-review

#3693 Unix: add `IN6ADDR_ANY_INIT`, `IN6ADDR_LOOPBACK_INIT`, `in6addr_any`, `in6addr_loopback`
  libc-test/semver/unix.txt
  src/unix/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3798 Linux: add a new syscall `SYS_mseal`
  libc-test/build.rs
  libc-test/semver/linux-i686.txt
  libc-test/semver/linux-powerpc.txt
  libc-test/semver/linux-s390x.txt
  libc-test/semver/linux-x86_64.txt
  src/unix/linux_like/linux/gnu/b32/arm/mod.rs
  src/unix/linux_like/linux/gnu/b32/powerpc.rs
  src/unix/linux_like/linux/gnu/b32/x86/mod.rs
  src/unix/linux_like/linux/gnu/b64/aarch64/mod.rs
  src/unix/linux_like/linux/gnu/b64/s390x.rs
  src/unix/linux_like/linux/gnu/b64/x86_64/not_x32.rs
  src/unix/linux_like/linux/musl/b32/arm/mod.rs
  src/unix/linux_like/linux/musl/b32/powerpc.rs
  src/unix/linux_like/linux/musl/b64/aarch64/mod.rs
  src/unix/linux_like/linux/musl/b64/s390x.rs
  src/unix/linux_like/linux/musl/b64/x86_64/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3832 [0.2] Apple: add `_NSGetArgv`, `_NSGetArgc` and `_NSGetProgname`
  libc-test/semver/apple.txt
  src/unix/bsd/apple/mod.rs
Labels: S-waiting-on-review

#3833 [0.2] Backport two pull requests
  libc-test/semver/netbsd.txt
  libc-test/semver/unix.txt
  src/unix/bsd/netbsdlike/netbsd/mod.rs
  src/unix/mod.rs
Labels: S-waiting-on-review

#3834 Revert "openbsd/netbsd factorise getnameinfo."
  src/unix/bsd/netbsdlike/mod.rs
  src/unix/bsd/netbsdlike/netbsd/mod.rs
  src/unix/bsd/netbsdlike/openbsd/mod.rs
Labels: S-waiting-on-review

#3836 Update CHANGELOG.md for 0.2.156
  CHANGELOG.md
Labels: S-waiting-on-review

#3786 hurd: Add missing struct __timeval for 64bit support
  src/unix/hurd/mod.rs
Labels: S-waiting-on-author, stable-nominated

#3779 Add missing constants for Android
  ci/android-install-ndk.sh
  libc-test/semver/android-aarch64.txt
  libc-test/semver/android-arm.txt
  libc-test/semver/android-i686.txt
  libc-test/semver/android-riscv64.txt
  libc-test/semver/android-x86_64.txt
  libc-test/semver/android.txt
  src/unix/linux_like/android/b32/arm.rs
  src/unix/linux_like/android/b32/x86/mod.rs
  src/unix/linux_like/android/b64/aarch64/mod.rs
  src/unix/linux_like/android/b64/mod.rs
  src/unix/linux_like/android/b64/riscv64/mod.rs
  src/unix/linux_like/android/b64/x86_64/mod.rs
  src/unix/linux_like/android/mod.rs
Labels: S-waiting-on-review

#3669 Add htonl, htons, ntohl, ntohs
  libc-test/semver/unix.txt
  src/unix/mod.rs
Labels: S-waiting-on-review

#3831 OpenBSD: add sendmmsg and recvmmsg support.
  libc-test/semver/openbsd.txt
  src/unix/bsd/netbsdlike/mod.rs
  src/unix/bsd/netbsdlike/netbsd/mod.rs
Labels: S-waiting-on-author, stable-nominated

#3840 TEEOS: Fix octal notation for O_* constants
  src/teeos/mod.rs
  src/unix/linux_like/linux/uclibc/mod.rs
  src/unix/linux_like/linux/uclibc/x86_64/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3842 Add RUSTC_WRAPPER support to build script
  build.rs
Labels: S-waiting-on-review, stable-nominated

#3841 [0.2] TEEOS: Fix octal notation for O_* constants
  src/teeos/mod.rs
  src/unix/linux_like/linux/uclibc/mod.rs
  src/unix/linux_like/linux/uclibc/x86_64/mod.rs
Labels: S-waiting-on-review

#3843 Unix: add `aligned_alloc`
  libc-test/build.rs
  libc-test/semver/unix.txt
  src/unix/mod.rs
Labels: S-waiting-on-review

#3845 [0.2] Add RUSTC_WRAPPER support to build script
  build.rs
Labels: S-waiting-on-review

#3837 Remove `Debug` impls from tpacket_* structs
  src/unix/linux_like/linux/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3849 add the `mq_notify` glibc wrapper for the `SYS_mq_notify` syscall
  libc-test/semver/linux-gnu.txt
  src/unix/linux_like/linux/gnu/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3851 [0.2] Backport three pull requests
  libc-test/build.rs
  libc-test/semver/android.txt
  libc-test/semver/fuchsia.txt
  libc-test/semver/linux.txt
  libc-test/semver/solarish.txt
  src/fuchsia/mod.rs
  src/unix/linux_like/android/mod.rs
  src/unix/linux_like/linux/mod.rs
  src/unix/mod.rs
  src/unix/solarish/mod.rs
Labels: S-waiting-on-review

#3852 [0.2] Backport two FreeBSD-related pull requests
  build.rs
  libc-test/build.rs
  libc-test/semver/freebsd.txt
  src/unix/bsd/freebsdlike/freebsd/mod.rs
Labels: S-waiting-on-review

#3853 [main] Apply two pull requests to main
  libc-test/semver/dragonfly.txt
  src/unix/bsd/freebsdlike/freebsd/mod.rs
  src/unix/bsd/freebsdlike/mod.rs
  src/unix/linux_like/linux/mod.rs
Labels: S-waiting-on-review

#3854 WASI: fix missing `Iterator` with `rustc-dep-of-std`
  src/wasi.rs
Labels: S-waiting-on-review, stable-nominated

#3856 WASI: fix missing `Iterator` with `rustc-dep-of-std`
  src/wasi.rs
Labels: S-waiting-on-review

#3855 fix clippy warnings
  build.rs
  src/unix/bsd/apple/mod.rs
  src/unix/bsd/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3844 Add missing `NFT_CT_*` constants to Linux/Android
  libc-test/semver/android.txt
  libc-test/semver/linux-gnu.txt
  src/unix/linux_like/android/mod.rs
  src/unix/linux_like/linux/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3858 add missing error numbers for HermitOS
  libc-test/semver/hermit.txt
  src/hermit.rs
Labels: S-waiting-on-author, stable-nominated

#3861 VxWorks: Add some functions from `vxCpuLib.h` and `taskLib.h`
  src/vxworks/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3869 Re-enable testing of WASI on CI
  .github/workflows/full_ci.yml
  build.rs
  ci/docker/wasm32-wasi/Dockerfile
  ci/docker/wasm32-wasi/clang.sh
  ci/docker/wasm32-wasip1/Dockerfile
  libc-test/build.rs
  src/wasi.rs
Labels: S-waiting-on-review, O-wasi, stable-nominated

#3870 Add `wasm32-wasip2` to the test matrix on CI
  .github/workflows/full_ci.yml
  ci/docker/wasm32-wasip1/Dockerfile
  ci/docker/wasm32-wasip2/Dockerfile
  ci/wasi.sh
Labels: S-waiting-on-author, stable-nominated

#3871 [0.2] Backport four pull requests
  libc-test/semver/android.txt
  libc-test/semver/linux-gnu.txt
  libc-test/semver/unix.txt
  src/unix/align.rs
  src/unix/hurd/mod.rs
  src/unix/linux_like/android/mod.rs
  src/unix/linux_like/linux/gnu/mod.rs
  src/unix/linux_like/linux/mod.rs
  src/unix/mod.rs
  src/unix/no_align.rs
Labels: S-waiting-on-review

#3873 [0.2] Backport two pull requests
  libc-test/semver/hermit.txt
  src/hermit.rs
  src/vxworks/mod.rs
Labels: S-waiting-on-review

#3872 [main] Apply three pull requests to main
  build.rs
  libc-test/semver/android-aarch64.txt
  libc-test/semver/android.txt
  src/unix/bsd/apple/mod.rs
  src/unix/bsd/mod.rs
  src/unix/linux_like/android/b64/aarch64/mod.rs
  src/unix/linux_like/android/mod.rs
  src/unix/mod.rs
Labels: S-waiting-on-review

#3874 [main] Apply three pull requests to main
  libc-test/semver/android.txt
  libc-test/semver/freebsd.txt
  libc-test/semver/linux.txt
  src/unix/aix/mod.rs
  src/unix/bsd/freebsdlike/mod.rs
  src/unix/linux_like/android/mod.rs
  src/unix/linux_like/linux/mod.rs
  src/unix/nto/mod.rs
Labels: S-waiting-on-review

#3876 [0.2] Backport of three pull requests
  libc-test/semver/openbsd.txt
  src/unix/bsd/netbsdlike/mod.rs
  src/unix/bsd/netbsdlike/netbsd/mod.rs
  src/unix/linux_like/linux/gnu/mod.rs
  src/unix/linux_like/linux/mod.rs
  src/unix/linux_like/linux/musl/mod.rs
  src/unix/linux_like/linux/uclibc/mod.rs
  src/vxworks/mod.rs
Labels: S-waiting-on-review

#3877 [0.2] Backport of two pull requests
  .github/workflows/full_ci.yml
  build.rs
  ci/docker/wasm32-wasi/Dockerfile
  ci/docker/wasm32-wasi/clang.sh
  ci/docker/wasm32-wasip1/Dockerfile
  ci/docker/wasm32-wasip2/Dockerfile
  ci/wasi.sh
  libc-test/build.rs
  src/wasi.rs
Labels: S-waiting-on-review

#3878 [main] Apply three pull requests to `main`
  ci/build.sh
  libc-test/Cargo.toml
  libc-test/build.rs
  src/unix/linux_like/linux/uclibc/mod.rs
Labels: S-waiting-on-review

#3881 Lower the MSRV to 1.63
  .github/workflows/full_ci.yml
  Cargo.toml
  README.md
  src/unix/bsd/apple/mod.rs
Labels: S-waiting-on-review

#3882 [main] Apply two pull requests to main
  libc-test/build.rs
  libc-test/semver/android.txt
  libc-test/semver/linux.txt
  libc-test/semver/netbsd.txt
  libc-test/semver/openbsd.txt
  src/unix/bsd/apple/mod.rs
  src/unix/bsd/freebsdlike/mod.rs
  src/unix/bsd/mod.rs
  src/unix/linux_like/android/mod.rs
  src/unix/linux_like/linux/mod.rs
Labels: S-waiting-on-review

#3884 [main]: Move strftime, strftime_l, strptime to linux_like
  libc-test/semver/linux-gnu.txt
  libc-test/semver/linux-musl.txt
  libc-test/semver/linux.txt
  src/unix/linux_like/linux/gnu/mod.rs
  src/unix/linux_like/linux/musl/mod.rs
  src/unix/linux_like/mod.rs
Labels: S-waiting-on-review

#3885 [main] add preadv2/pwritev2 to linux musl (1.2.5 min.)
  libc-test/build.rs
  libc-test/semver/linux-musl.txt
  src/unix/linux_like/linux/musl/mod.rs
Labels: S-waiting-on-review

#3886 [main] macOS: add `os_sync_wait_on_address` and related definitions
  libc-test/build.rs
  libc-test/semver/apple.txt
  src/unix/bsd/apple/mod.rs
Labels: S-waiting-on-review

#3883 Add missing `NOTE_*` constants to apple
  libc-test/semver/apple.txt
  src/unix/bsd/apple/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3888 [0.2] Backport three pull requests
  libc-test/build.rs
  libc-test/semver/apple.txt
  libc-test/semver/linux-i686.txt
  libc-test/semver/linux-powerpc.txt
  libc-test/semver/linux-s390x.txt
  libc-test/semver/linux-x86_64.txt
  src/unix/bsd/apple/mod.rs
  src/unix/linux_like/linux/gnu/b32/arm/mod.rs
  src/unix/linux_like/linux/gnu/b32/powerpc.rs
  src/unix/linux_like/linux/gnu/b32/x86/mod.rs
  src/unix/linux_like/linux/gnu/b64/aarch64/mod.rs
  src/unix/linux_like/linux/gnu/b64/s390x.rs
  src/unix/linux_like/linux/gnu/b64/x86_64/not_x32.rs
  src/unix/linux_like/linux/gnu/b64/x86_64/x32.rs
  src/unix/linux_like/linux/musl/b32/arm/mod.rs
  src/unix/linux_like/linux/musl/b32/powerpc.rs
  src/unix/linux_like/linux/musl/b32/x86/mod.rs
  src/unix/linux_like/linux/musl/b64/aarch64/mod.rs
  src/unix/linux_like/linux/musl/b64/s390x.rs
  src/unix/linux_like/linux/musl/b64/x86_64/mod.rs
Labels: S-waiting-on-review

#3889 [main] cirrus-ci: use matrix to remove redundant parts on building bsds
  .cirrus.yml
Labels: S-waiting-on-review

#3891 ci: clean up workflow
  .github/workflows/full_ci.yml
Labels: S-waiting-on-review
