Repository rust-lang/libc, pull requests merged in 2024-01, with the labels that each got.

#3509 clock_nanosleep for dragonflybsd, moving constants freebsd only too.
  libc-test/semver/dragonfly.txt
  src/unix/bsd/freebsdlike/freebsd/mod.rs
  src/unix/bsd/freebsdlike/mod.rs
Labels: S-waiting-on-bors

#3503 solarish add fcntl's O_DIRECT constant.
  src/unix/solarish/mod.rs
Labels: S-waiting-on-bors

#3511 Unpin cc dependency version
  libc-test/Cargo.toml
Labels: S-waiting-on-bors

#3512 redox: add openpty, login_tty, TIOCSCTTY, and organize functions
  libc-test/semver/redox.txt
  src/unix/redox/mod.rs
Labels: S-waiting-on-bors

#3343 Move all seccomp consts and structs into top-level mod
  libc-test/build.rs
  libc-test/semver/linux.txt
  src/unix/linux_like/linux/gnu/b32/arm/mod.rs
  src/unix/linux_like/linux/gnu/b32/csky/mod.rs
  src/unix/linux_like/linux/gnu/b32/x86/mod.rs
  src/unix/linux_like/linux/gnu/b64/aarch64/mod.rs
  src/unix/linux_like/linux/gnu/b64/x86_64/mod.rs
  src/unix/linux_like/linux/mod.rs
Labels: S-waiting-on-bors

#3508 freebsd 15 support proposal.
  .cirrus.yml
  build.rs
  libc-test/build.rs
  src/unix/bsd/freebsdlike/freebsd/freebsd15/b64.rs
  src/unix/bsd/freebsdlike/freebsd/freebsd15/mod.rs
  src/unix/bsd/freebsdlike/freebsd/freebsd15/x86_64.rs
  src/unix/bsd/freebsdlike/freebsd/mod.rs
Labels: S-waiting-on-bors

#3514 Prepare workflow for merge queue
  .github/workflows/full_ci.yml
Labels: S-waiting-on-bors

#3516 Allow dead_code on `clockid_t`
  src/psp.rs
  src/wasi.rs
Labels: S-waiting-on-bors

#3515 Add more items from `include/linux/sched.h` header
  libc-test/build.rs
  src/unix/linux_like/linux/mod.rs
Labels: S-waiting-on-bors

#3517 fix typo
  src/teeos/mod.rs
Labels: S-waiting-on-bors

#3518 Add sigsuspend to more targets: bsd, haiku, and solarish
  libc-test/semver/apple.txt
  libc-test/semver/dragonfly.txt
  libc-test/semver/freebsd.txt
  libc-test/semver/netbsd.txt
  libc-test/semver/openbsd.txt
  src/unix/bsd/mod.rs
  src/unix/haiku/mod.rs
  src/unix/solarish/mod.rs
Labels: S-waiting-on-bors

#3519 Tweak libc-0.2 CI
  .github/workflows/full_ci.yml
Labels: S-waiting-on-bors

#3520 fuchsia adding pthread_set/getname_np
  libc-test/semver/fuchsia.txt
  src/fuchsia/mod.rs
Labels: S-waiting-on-bors

#3510 Prepare docs for libc v0.3
  CONTRIBUTING.md
  README.md
Labels: S-waiting-on-bors

#3521 Merge main into libc-0.2
  .github/workflows/full_ci.yml
  CONTRIBUTING.md
  README.md
  libc-test/build.rs
  libc-test/semver/apple.txt
  libc-test/semver/dragonfly.txt
  libc-test/semver/freebsd.txt
  libc-test/semver/fuchsia.txt
  libc-test/semver/netbsd.txt
  libc-test/semver/openbsd.txt
  src/fuchsia/mod.rs
  src/psp.rs
  src/teeos/mod.rs
  src/unix/bsd/mod.rs
  src/unix/haiku/mod.rs
  src/unix/linux_like/linux/mod.rs
  src/unix/solarish/mod.rs
  src/wasi.rs
Labels: S-waiting-on-review, libc-0.2-pre-merge-ci

#3522 Prepare release for v0.2.152
  Cargo.toml
  libc-test/Cargo.toml
Labels: S-waiting-on-review

#3523 Remove PSP-related code
  Cargo.toml
  ci/build.sh
  src/lib.rs
  src/psp.rs
Labels: S-waiting-on-bors

#3524 Bump MSRV to 1.71
  .github/workflows/bors.yml
  .github/workflows/full_ci.yml
Labels: S-waiting-on-bors

#3495 Simplify build.rs by using the question mark operator
  build.rs
Labels: S-waiting-on-bors

#3466 update epoll constants to match epoll_event struct
  src/unix/linux_like/mod.rs
Labels: breakage-candidate, S-waiting-on-bors

#3478 linux's sockaddr_vm update for kernel >= 5.11.
  libc-test/build.rs
  src/unix/linux_like/linux/mod.rs
Labels: breakage-candidate, S-waiting-on-bors

#3526 Remove inconv linking on apple
  libc-test/semver/apple.txt
  src/unix/bsd/apple/mod.rs
Labels: S-waiting-on-bors

#3356 Change `FD_SETSIZE` to `c_int`
  src/fuchsia/mod.rs
  src/unix/aix/mod.rs
  src/unix/bsd/apple/mod.rs
  src/unix/bsd/freebsdlike/mod.rs
  src/unix/bsd/mod.rs
  src/unix/bsd/netbsdlike/netbsd/mod.rs
  src/unix/bsd/netbsdlike/openbsd/mod.rs
  src/unix/haiku/mod.rs
  src/unix/hurd/mod.rs
  src/unix/linux_like/mod.rs
  src/unix/newlib/mod.rs
  src/unix/nto/mod.rs
  src/unix/redox/mod.rs
  src/unix/solarish/mod.rs
  src/wasi.rs
Labels: breakage-candidate, S-waiting-on-bors

#3213 utmpx api for linux musl + musl few build fixes.
  libc-test/semver/linux-gnu.txt
  libc-test/semver/linux-musl.txt
  src/unix/linux_like/linux/musl/mod.rs
Labels: S-waiting-on-bors

#3528 Remove the `use_std` feature
  Cargo.toml
  README.md
  build.rs
Labels: S-waiting-on-bors

#3530 Add additional Linux AF_PACKET options
  libc-test/build.rs
  libc-test/semver/linux.txt
  src/unix/linux_like/linux/mod.rs
Labels: S-waiting-on-bors

#3539 Add initial support for hppa-unknown-linux-gnu
  src/unix/linux_like/linux/align.rs
  src/unix/linux_like/linux/gnu/b32/hppa/align.rs
  src/unix/linux_like/linux/gnu/b32/hppa/mod.rs
  src/unix/linux_like/linux/gnu/b32/mod.rs
  src/unix/linux_like/linux/gnu/mod.rs
Labels: S-waiting-on-bors

#3541 Run full_ci on PRs temporalily
  .github/workflows/full_ci.yml
  .github/workflows/main.yml
Labels: S-waiting-on-review

#3542 Revert "Add initial support for hppa-unknown-linux-gnu"
  src/unix/linux_like/linux/align.rs
  src/unix/linux_like/linux/gnu/b32/hppa/align.rs
  src/unix/linux_like/linux/gnu/b32/hppa/mod.rs
  src/unix/linux_like/linux/gnu/b32/mod.rs
  src/unix/linux_like/linux/gnu/mod.rs
Labels: S-waiting-on-review

#3544 add target for loongarch64
  Cargo.toml
Labels: S-waiting-on-review

#3543 feat: IPV6_RECVHOPLIMIT & IP_RECVTTL for FreeBSD
  libc-test/semver/freebsd.txt
  src/unix/bsd/freebsdlike/freebsd/mod.rs
Labels: S-waiting-on-review

#3536 Add missing constants for Android
  libc-test/build.rs
  src/unix/linux_like/android/mod.rs
Labels: S-waiting-on-review

#3538 Fix broken vita std compilation by adding SOMAXCONN
  src/unix/newlib/vita/mod.rs
Labels: S-waiting-on-review

#3537 linux/uclibc completing siginfo fields.
  src/unix/linux_like/linux/uclibc/mod.rs
Labels: S-waiting-on-review

#3548 Add ioctl FS_IOC_{G,S}{ETVERSION,ETFLAGS} for LoongArch64
  src/unix/linux_like/linux/arch/generic/mod.rs
Labels: S-waiting-on-review

#3552 Add SOMAXCONN to vita on 0.2 (to fix std)
  src/unix/newlib/vita/mod.rs
Labels: S-waiting-on-review, libc-0.2-pre-merge-ci

#3551 Fix libc-tests for loongarch64
  libc-test/build.rs
  libc-test/semver/linux-aarch64.txt
  libc-test/semver/linux-i686.txt
  libc-test/semver/linux-mips.txt
  libc-test/semver/linux-powerpc.txt
  libc-test/semver/linux-powerpc64.txt
  libc-test/semver/linux-powerpc64le.txt
  libc-test/semver/linux-riscv64gc.txt
  libc-test/semver/linux-s390x.txt
  libc-test/semver/linux-sparc64.txt
  libc-test/semver/linux-x86_64.txt
  libc-test/semver/linux.txt
  src/unix/linux_like/linux/gnu/b64/loongarch64/mod.rs
Labels: S-waiting-on-review

#3547 fix ioctl FS_IOC_* version and flag of csky
  src/unix/linux_like/linux/arch/generic/mod.rs
Labels: S-waiting-on-review

#3557 Fix CI for v0.2
  .github/workflows/bors.yml
  .github/workflows/full_ci.yml
Labels: S-waiting-on-review

#3562 Fix CI
  .github/workflows/bors.yml
  .github/workflows/full_ci.yml
Labels: S-waiting-on-review

#3558 android: add missing syscall constants
  libc-test/semver/android-aarch64.txt
  libc-test/semver/android-i686.txt
  libc-test/semver/android-x86_64.txt
  libc-test/semver/android.txt
  src/unix/linux_like/android/b32/arm.rs
  src/unix/linux_like/android/b32/x86/mod.rs
  src/unix/linux_like/android/b64/aarch64/mod.rs
  src/unix/linux_like/android/b64/riscv64/mod.rs
  src/unix/linux_like/android/b64/x86_64/mod.rs
Labels: S-waiting-on-review

#3441 Added remaining linux/wireless.h struct and constants
  libc-test/build.rs
  libc-test/semver/linux.txt
  src/unix/linux_like/linux/mod.rs
Labels: S-waiting-on-review

#3533 Remove mach-related items
  libc-test/build.rs
  libc-test/semver/apple.txt
  src/macros.rs
  src/unix/bsd/apple/mod.rs
Labels: S-waiting-on-review

#3565 Remove some unsafe impls
  src/unix/linux_like/android/mod.rs
  src/unix/linux_like/linux/mod.rs
Labels: S-waiting-on-review

#3570 [Backport #3548] Add ioctl FS_IOC_{G,S}{ETVERSION,ETFLAGS} for LoongArch64
  src/unix/linux_like/linux/arch/generic/mod.rs
Labels: S-waiting-on-review

#3554 Backport of #3546 and update crate version to 0.2.153
  Cargo.toml
  libc-test/Cargo.toml
  libc-test/build.rs
  src/unix/linux_like/android/mod.rs
Labels: S-waiting-on-review
