Repository rust-lang/libc, pull requests merged in 2024-09, with the labels that each got.

#3893 Handle version output correctly when `clippy-driver` used
  build.rs
Labels: S-waiting-on-review, stable-nominated

#3868 Expose the "epoll_pwait2()" function
  libc-test/semver/linux-gnu.txt
  src/unix/linux_like/linux/gnu/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3892 Add wasm32-wasip2 definitions necessary for std::net support
  libc-test/build.rs
  libc-test/semver/wasi-p2.txt
  src/wasi/mod.rs
  src/wasi/p2.rs
Labels: S-waiting-on-review, stable-nominated

#3895 Change signal constants to c_int on espidf
  src/unix/newlib/espidf/mod.rs
Labels: stable-nominated, S-waiting-on-ci

#3480 adding tcp_info struct to linux musl/glibc.
  libc-test/build.rs
  libc-test/semver/linux-gnu.txt
  libc-test/semver/linux-musl.txt
  src/unix/linux_like/linux/gnu/mod.rs
  src/unix/linux_like/linux/musl/mod.rs
Labels: stable-nominated, S-waiting-on-ci

#3695 adding a handful of linux fanotify data types.
  libc-test/build.rs
  libc-test/semver/linux-gnu.txt
  libc-test/semver/linux.txt
  src/unix/linux_like/linux/gnu/mod.rs
  src/unix/linux_like/linux/mod.rs
Labels: stable-nominated, S-waiting-on-ci

#3897 Remove unneeded `extern crate`s and imports
  build.rs
  libc-test/build.rs
  libc-test/test/cmsg.rs
  libc-test/test/errqueue.rs
  libc-test/test/linux_elf.rs
  libc-test/test/linux_fcntl.rs
  libc-test/test/linux_if_arp.rs
  libc-test/test/linux_ipv6.rs
  libc-test/test/linux_kernel_version.rs
  libc-test/test/linux_strerror_r.rs
  libc-test/test/linux_termios.rs
  libc-test/test/main.rs
  libc-test/test/makedev.rs
  libc-test/test/semver.rs
  libc-test/test/sigrt.rs
Labels: S-waiting-on-review, stable-nominated

#3899 [0.2] Add wasm32-wasip2 definitions necessary for std::net support
  libc-test/build.rs
  libc-test/semver/wasi-p2.txt
  src/wasi/mod.rs
  src/wasi/p2.rs
Labels: S-waiting-on-review

#3901 [0.2] Expose the "epoll_pwait2()" function
  libc-test/semver/linux-gnu.txt
  src/unix/linux_like/linux/gnu/mod.rs
Labels: S-waiting-on-review

#3900 [0.2] Change signal constants to c_int on espidf
  src/unix/newlib/espidf/mod.rs
Labels: S-waiting-on-review

#3863 Revise network definitions for HorizonOS
  src/unix/newlib/horizon/mod.rs
  src/unix/newlib/mod.rs
Labels: S-waiting-on-author, stable-nominated

#3902 [0.2] Backport horizon network
  src/unix/newlib/horizon/mod.rs
  src/unix/newlib/mod.rs
Labels: S-waiting-on-review

#3903 Update `rustc_version_cmd`
  build.rs
Labels: S-waiting-on-review

#3866 Add port for RTEMS
  build.rs
  src/unix/newlib/mod.rs
  src/unix/newlib/rtems/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3930 Remove temporary file that was added by accident
  build-tmp.rs
Labels: S-waiting-on-review, stable-nominated

#3931 [0.2] Remove temporary file that was added by accident
  build-tmp.rs
Labels: S-waiting-on-review

#3919 redox: Make ino_t be c_ulonglong
  src/unix/redox/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3906 Add `getpwnam_r` and `getpwuid_r` to emscripten
  libc-test/semver/emscripten.txt
  src/unix/linux_like/emscripten/mod.rs
Labels: stable-nominated, S-waiting-on-ci

#3894 Fix alignment of uc_mcontext in ucontext_t on arm64 android
  src/unix/linux_like/android/b64/aarch64/align.rs
Labels: S-waiting-on-review, stable-nominated

#3915 Link to windows-sys crate
  README.md
Labels: S-waiting-on-author, stable-nominated

#3909 Initial support for NuttX
  build.rs
  src/unix/mod.rs
  src/unix/nuttx/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3939 Fix "struct stat" on 32-bit FreeBSD 12+
  src/unix/bsd/freebsdlike/freebsd/arm.rs
  src/unix/bsd/freebsdlike/freebsd/freebsd11/b32.rs
  src/unix/bsd/freebsdlike/freebsd/freebsd11/mod.rs
  src/unix/bsd/freebsdlike/freebsd/freebsd12/mod.rs
  src/unix/bsd/freebsdlike/freebsd/freebsd13/b64.rs
  src/unix/bsd/freebsdlike/freebsd/freebsd13/mod.rs
  src/unix/bsd/freebsdlike/freebsd/freebsd14/b64.rs
  src/unix/bsd/freebsdlike/freebsd/freebsd14/mod.rs
  src/unix/bsd/freebsdlike/freebsd/freebsd15/b64.rs
  src/unix/bsd/freebsdlike/freebsd/freebsd15/mod.rs
  src/unix/bsd/freebsdlike/freebsd/powerpc.rs
  src/unix/bsd/freebsdlike/freebsd/powerpc64.rs
  src/unix/bsd/freebsdlike/freebsd/x86.rs
Labels: S-waiting-on-review, main-needs-cherry-pick

#3911 Add `AT_EACCESS` to emscripten
  libc-test/semver/emscripten.txt
  src/unix/linux_like/emscripten/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3927 Add missing definitions on NetBSD
  libc-test/semver/netbsd.txt
  src/unix/bsd/netbsdlike/netbsd/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3950 Fix CI for FreeBSD 15
  libc-test/build.rs
  libc-test/semver/freebsd.txt
  src/unix/bsd/freebsdlike/freebsd/mod.rs
Labels: S-waiting-on-review

#3929 Feat(Apple): Add the LOCAL_PEERTOKEN socket option
  libc-test/semver/apple.txt
  src/unix/bsd/apple/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3952 Fix CI for FreeBSD 15, on libc-0.2 branch
  libc-test/build.rs
  src/unix/bsd/freebsdlike/freebsd/mod.rs
Labels: S-waiting-on-review

#3941 Android: Added PR_GET_NAME and PR_SET_NAME
  libc-test/semver/android.txt
  src/unix/linux_like/android/mod.rs
Labels: S-waiting-on-review, stable-nominated
