Repository rust-lang/libc, pull requests merged in 2024-10, with the labels that each got.

#3938 linux: Make elf name type constants always available
  libc-test/semver/linux-gnu.txt
  libc-test/semver/linux.txt
  src/unix/linux_like/linux/gnu/mod.rs
  src/unix/linux_like/linux/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3848 Add ucontext_t for freebsd-aarch64
  libc-test/semver/freebsd-x86_64.txt
  libc-test/semver/freebsd.txt
  src/unix/bsd/freebsdlike/freebsd/arm.rs
  src/unix/bsd/freebsdlike/freebsd/mod.rs
  src/unix/bsd/freebsdlike/freebsd/powerpc.rs
  src/unix/bsd/freebsdlike/freebsd/powerpc64.rs
  src/unix/bsd/freebsdlike/freebsd/x86.rs
  src/unix/bsd/freebsdlike/freebsd/x86_64/align.rs
Labels: S-waiting-on-review, stable-nominated

#3953 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: S-waiting-on-review, stable-nominated

#3954 Sort linux-musl.txt
  libc-test/semver/linux-musl.txt
Labels: S-waiting-on-review

#3912 Add `getgrgid`, `getgrnam`, `getgrnam_r` and `getgrgid_r` for emscripten
  libc-test/semver/emscripten.txt
  src/unix/linux_like/emscripten/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3540 [0.2] Add additional Linux AF_PACKET options
  libc-test/build.rs
  libc-test/semver/linux.txt
  src/unix/linux_like/linux/align.rs
  src/unix/linux_like/linux/mod.rs
  src/unix/linux_like/linux/no_align.rs
Labels: S-waiting-on-review

#3913 Add mach_error_string (and mach_error_t)
  libc-test/semver/apple.txt
  src/unix/bsd/apple/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3908 Add missing musl utmpx.h constants
  libc-test/semver/linux-musl.txt
  src/unix/linux_like/linux/musl/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3946 Fix the definition of struct stat on 32-bit FreeBSD 12+
  src/unix/bsd/freebsdlike/freebsd/arm.rs
  src/unix/bsd/freebsdlike/freebsd/freebsd11/b32.rs
  src/unix/bsd/freebsdlike/freebsd/freebsd11/mod.rs
  src/unix/bsd/freebsdlike/freebsd/freebsd12/mod.rs
  src/unix/bsd/freebsdlike/freebsd/freebsd13/b64.rs
  src/unix/bsd/freebsdlike/freebsd/freebsd13/mod.rs
  src/unix/bsd/freebsdlike/freebsd/freebsd14/b64.rs
  src/unix/bsd/freebsdlike/freebsd/freebsd14/mod.rs
  src/unix/bsd/freebsdlike/freebsd/freebsd15/b64.rs
  src/unix/bsd/freebsdlike/freebsd/freebsd15/mod.rs
  src/unix/bsd/freebsdlike/freebsd/powerpc.rs
  src/unix/bsd/freebsdlike/freebsd/powerpc64.rs
  src/unix/bsd/freebsdlike/freebsd/x86.rs
Labels: S-waiting-on-review

#3920 Fix ESP-IDF constants and structs
  src/unix/newlib/espidf/mod.rs
  src/unix/newlib/generic.rs
  src/unix/newlib/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3846 Apple: Add additional `pthread` APIs
  libc-test/semver/apple.txt
  src/unix/bsd/apple/b32/mod.rs
  src/unix/bsd/apple/b64/mod.rs
  src/unix/bsd/apple/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3935 Add RISC-V vxworks target specific constants
  Cargo.toml
  ci/build.sh
  src/vxworks/mod.rs
  src/vxworks/riscv32.rs
  src/vxworks/riscv64.rs
Labels: S-waiting-on-review, stable-nominated

#3720 Add iopl/ioperm to all linuxes
  libc-test/semver/linux-i686.txt
  libc-test/semver/linux-x86_64.txt
  src/unix/linux_like/linux/gnu/b64/x86_64/mod.rs
  src/unix/linux_like/linux/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3867 adding new illumos ptsname_r call.
  libc-test/semver/illumos.txt
  src/unix/solarish/illumos.rs
  src/unix/solarish/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3936 [solarish/freebsd] add a few missing constants and functions
  libc-test/semver/freebsd.txt
  libc-test/semver/illumos.txt
  src/unix/bsd/freebsdlike/freebsd/mod.rs
  src/unix/solarish/illumos.rs
  src/unix/solarish/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3949 [musl] add posix_spawn chdir functions
  libc-test/semver/linux-musl.txt
  src/unix/linux_like/linux/musl/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3966 [0.2] backports
  README.md
  libc-test/build.rs
  libc-test/semver/emscripten.txt
  libc-test/semver/linux-gnu.txt
  libc-test/semver/linux-musl.txt
  libc-test/semver/linux.txt
  src/unix/linux_like/emscripten/mod.rs
  src/unix/linux_like/linux/gnu/mod.rs
  src/unix/linux_like/linux/mod.rs
  src/unix/linux_like/linux/musl/mod.rs
  src/unix/redox/mod.rs
Labels: S-waiting-on-review

#3925 fcntl add F_TRANSFEREXTENTS for macos.
  libc-test/semver/apple.txt
  src/unix/bsd/apple/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3945 arc4random api for haiku
  libc-test/build.rs
  src/unix/haiku/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3714 Add RTF_*, RTA_*, RTAX_*, RTM_* definitions on BSDs
  libc-test/semver/dragonfly.txt
  libc-test/semver/freebsd.txt
  libc-test/semver/netbsd.txt
  libc-test/semver/openbsd.txt
  src/unix/bsd/apple/mod.rs
  src/unix/bsd/freebsdlike/dragonfly/mod.rs
  src/unix/bsd/freebsdlike/freebsd/mod.rs
  src/unix/bsd/freebsdlike/mod.rs
  src/unix/bsd/mod.rs
  src/unix/bsd/netbsdlike/netbsd/mod.rs
  src/unix/bsd/netbsdlike/openbsd/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3968 [0.2] Backports
  build.rs
  libc-test/semver/apple.txt
  libc-test/semver/emscripten.txt
  libc-test/semver/linux-i686.txt
  libc-test/semver/linux-musl.txt
  libc-test/semver/linux-x86_64.txt
  src/unix/bsd/apple/b32/mod.rs
  src/unix/bsd/apple/b64/mod.rs
  src/unix/bsd/apple/mod.rs
  src/unix/linux_like/emscripten/mod.rs
  src/unix/linux_like/linux/gnu/b64/x86_64/mod.rs
  src/unix/linux_like/linux/mod.rs
  src/unix/linux_like/linux/musl/mod.rs
  src/unix/mod.rs
  src/unix/newlib/mod.rs
  src/unix/newlib/rtems/mod.rs
  src/unix/nuttx/mod.rs
Labels: S-waiting-on-review

#3969 [0.2] Backports
  .github/PULL_REQUEST_TEMPLATE.md
  libc-test/semver/android.txt
  libc-test/semver/apple.txt
  libc-test/semver/emscripten.txt
  libc-test/semver/linux-gnu.txt
  libc-test/semver/linux.txt
  src/unix/bsd/apple/mod.rs
  src/unix/linux_like/android/mod.rs
  src/unix/linux_like/emscripten/mod.rs
  src/unix/linux_like/linux/gnu/mod.rs
  src/unix/linux_like/linux/mod.rs
  src/unix/newlib/espidf/mod.rs
  src/unix/newlib/generic.rs
  src/unix/newlib/mod.rs
Labels: S-waiting-on-review

#3973 Add getentropy to RTEMS
  src/unix/newlib/rtems/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3685 redox: correct EPOLL constants
  src/unix/redox/mod.rs
Labels: S-waiting-on-author, stable-nominated

#3974 Temporarily disable CI on FreeBSD 15
  .cirrus.yml
Labels: S-waiting-on-review, stable-nominated

#3970 unbreak OpenBSD after #3714 by properly define RTF_FMASK
  src/unix/bsd/netbsdlike/openbsd/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3963 pthread constants and functions for VxWorks
  src/vxworks/mod.rs
Labels: S-waiting-on-review

#3977 semver/linux-musl: Remove outdated "TODO: musl" comment
  libc-test/semver/linux-musl.txt
Labels: S-waiting-on-review, stable-nominated

#3980 [0.2] Backports
  Cargo.toml
  ci/build.sh
  libc-test/semver/dragonfly.txt
  libc-test/semver/freebsd.txt
  libc-test/semver/illumos.txt
  libc-test/semver/linux-musl.txt
  libc-test/semver/netbsd.txt
  libc-test/semver/openbsd.txt
  src/unix/bsd/apple/mod.rs
  src/unix/bsd/freebsdlike/dragonfly/mod.rs
  src/unix/bsd/freebsdlike/freebsd/mod.rs
  src/unix/bsd/freebsdlike/mod.rs
  src/unix/bsd/mod.rs
  src/unix/bsd/netbsdlike/netbsd/mod.rs
  src/unix/bsd/netbsdlike/openbsd/mod.rs
  src/unix/solarish/illumos.rs
  src/unix/solarish/mod.rs
  src/vxworks/mod.rs
  src/vxworks/riscv32.rs
  src/vxworks/riscv64.rs
Labels: S-waiting-on-review

#3982 [0.2] Backports
  libc-test/build.rs
  libc-test/semver/linux-musl.txt
  libc-test/semver/unix.txt
  src/unix/mod.rs
Labels: S-waiting-on-review

#3983 unbreak OpenBSD after #3937
  src/unix/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3984 [0.2] Backport bsd fix
  src/unix/mod.rs
Labels: S-waiting-on-review

#3992 hurd: fix definition of utsname struct
  src/unix/hurd/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3785 hurd: Fix st_dev name
  src/unix/hurd/mod.rs
Labels: stable-nominated, S-waiting-on-ci

#3994 Fix the build on armv7-unknown-freebsd
  src/unix/bsd/freebsdlike/freebsd/arm.rs
Labels: S-waiting-on-review, stable-nominated

#3995 armv7-unknown-freebsd: fix test errors regarding __gregset_t
  libc-test/build.rs
Labels: S-waiting-on-review, stable-nominated

#3993 Update esp-idf time flag
  build.rs
  src/unix/newlib/mod.rs
Labels: S-waiting-on-review

#3989 RTEMS export arc4random
  src/unix/newlib/rtems/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3948 Fix tests on FreeBSD x86
  src/unix/bsd/freebsdlike/dragonfly/mod.rs
  src/unix/bsd/freebsdlike/freebsd/aarch64.rs
  src/unix/bsd/freebsdlike/freebsd/arm.rs
  src/unix/bsd/freebsdlike/freebsd/freebsd13/mod.rs
  src/unix/bsd/freebsdlike/freebsd/freebsd14/mod.rs
  src/unix/bsd/freebsdlike/freebsd/freebsd15/mod.rs
  src/unix/bsd/freebsdlike/freebsd/mod.rs
  src/unix/bsd/freebsdlike/freebsd/powerpc.rs
  src/unix/bsd/freebsdlike/freebsd/powerpc64.rs
  src/unix/bsd/freebsdlike/freebsd/riscv64.rs
  src/unix/bsd/freebsdlike/freebsd/x86.rs
  src/unix/bsd/freebsdlike/freebsd/x86_64/mod.rs
  src/unix/bsd/freebsdlike/mod.rs
Labels: S-waiting-on-review, stable-nominated

#3990 illumos adding syncfs.
  libc-test/semver/illumos.txt
  src/unix/solarish/illumos.rs
Labels: S-waiting-on-review, stable-nominated

#3981 Add wasm32-wasip2 definitions necessary for socket2 support
  libc-test/semver/wasi-p2.txt
  src/wasi/p2.rs
Labels: S-waiting-on-review, stable-nominated
